### ISSUE TITLE
Consider adding built-in websocket support!

### ISSUE THREAD

**Issue by kennethreitz** [benoitc/gunicorn#1015]
https://pypi.python.org/pypi/gevent-websocket/

**Comment by tilgovi** [comment]
I think it'd be awesome if we could provide something. I've used SockJS with gevent and gevent-websocket and switched to ws4py and it'd be awesome to have something that just works.

**Comment by GMLudo** [comment]
I've no doubt that you'll have a something to show at the end.

Nevertheless, on production, with a daemon with a lot of code, if you have an issue with the monkey-patching of Gevent and WSGI, at least to my experience, it will be difficult to debug that. I'd experimented some strange issues with grequests before to abandon that. Certainly I'm not have the same dev level as you guys to debug. Nevertheless, if I've issues to debug, a lot of developers will have more issues.

Guys, you do what you want, but sincerely, at least to me, it looks like a frankenstein solution.
At least to me, if you want to do WebSockets without to shoot your foot with Gunicorn:

1. Don't use WSGI. WSGI is thought for Request/Response model, not for WebSockets use case. I understand the goal of WSGI to have several WSGI applications in the same daemon instance. Now, who use that on production ? You have more constraints to do that instead of to have several daemons and use HAproxy or Nginx to distribute HTTP requests based on URI. With that, you can upgrade/restart/... easier your daemons. At least to me, WSGI is an unnecessary layer. Nevertheless, if you really want to keep WSGI, it's necessary to "upgrade" WSGI standard to support in the same time bidirectional exchanges and explicit async pattern.
2. You already have two workers to do WebSockets:
    1. For HTTP and WebSockets support only: aiohttp.web worker: http://aiohttp.readthedocs.org/en/v0.15.3/gunicorn.html
    2. For any protocol, because, at least to my use cases, the world isn't only HTTP protocol: API-Hour worker: https://github.com/Eyepea/API-Hour#api-hour

FYI, I you think that API-Hour and/or AsyncIO are too young for production, I've a battery of WebSockets soldiers to track more than 3 millions of SIP calls by month via Asterisk servers. Each SIP call generate several WebSockets events to follow calls on a WebUI for clients.

BTW, I'm working on a more generic worker for Gunicorn, based on API-Hour worker. I've show that to @benoitc during PyCON, I'll publish that ASAP.

I hope that I don't shock too much some popular believes in Python community with my message, nevertheless, why I must shut up my opinions when its aren't mainstream ideas ? In the past, most people believes that the Earth was flat, it wasn't meant it was true.

Finally, @kennethreitz, I'm taking the opportunity to discuss with you to thank you about two points:

1. Requests. Even if now I use aiohttp.client instead of Requests, aiohttp.client takes some inspiration from clean API of Requests.
2. More generally, for the promotion of "For humans" spirit in Python community: I use that often inside my company or in AsyncIO community to try to have most as possible to keep things simple, because most developers have the tendency to provide solutions more complicated than necessary. Several interesting side effects:
    1. Easier/quicker to code => more developers can code
    2. Easier/quicker to debug => more developers can debug
    3. More efficient => Need less computer resources => it's more economic and more ecologic

Have a nice week-end.

**Comment by kennethreitz** [comment]
:sparkles: :cake: :sparkles:

**Comment by tilgovi** [comment]
Thanks for your thoughts, @GMLudo.

I agree that often separate daemons is the best solution to problems. In particular, your use case sounds like it has a large number of WebSocket connections but a much smaller number of regular HTTP requests, so it might make sense to scale them independently.

I think there are other things WSGI is for, though, and it's not really about multiplexing handlers. That's one thing made possible by the WSGI interface. Another is composition of middlewares.

I can see some value in working out with the rest of the WSGI community what is expected in the environment to signal to servers that the upgrade has occurred and to pass the socket to the WebSocket handler.

I suppose the question is whether the Gunicorn worker and configuration model is useful enough to want to use with WebSockets generally, whether or not your application includes non-WebSocket routes. If it's not useful enough, then the recommendation is to not use Gunicorn for WebSockets. If it is useful enough, then Gunicorn would benefit from some WSGI-level protocol around WebSocket hand-off so that we start to move away from the current state of affairs that has some issues:

- WebSocket projects I see in Python often have several different integration helpers for different WSGI servers.
- As a result, applications become bound to particular servers because they have to choose to use one integration.

So, where do we go from here?

**Comment by benoitc** [comment]
So first gunicorn already embed the logic to handle long connections and upgrade a simple wsgi request like show these examples:

https://github.com/benoitc/gunicorn/tree/master/examples/websocket

It's basically a way to tell to gunicorn to give up on that sockets and return to accepting. The reason people are after that using gevent or eventlet is mostly because of their ability to switch the thread context at a given time. The good reason to still use WSGI here is to allow an application to decide if it has to upgrade a request to websockets or do anything else, based on the path, some header, whatever. Having a full HTTP worker is imo orthogonal there. We could have both until the logic is generic.

If we want to embed the websockets logic and later the HTTP2 logic we should rather introduce an api available at the application level that would allows to upgrade to the websockets and then interact with the server. 

Then if we can we could provide different ways to handle multiple connections at once: by default using asyncio on py3 or any other alternatives like fibers, greenlets based.

Thoughts? (Sorry if i'm unclear, don't hesitate to ask, I still not recovered completely from my illness last 2 weeks).

**Comment by GMLudo** [comment]
@tilgovi and @benoitc: Thanks for your remarks, I don't forget you, but I'm lack of time today. I'll answer you tomorrow.

**Comment by GMLudo** [comment]
Hello guys,

As you have understand, for my personal needs, I need nothing more in Gunicorn.

I was a little bit provocative to have some reactions, nevertheless, I sincerely think that something should be done for WSGI users.

Since the apparition of WSGI, you have now WebSockets, HTTP/2 and also async pattern integrated in Python, certainly with special keywords for the next version.

At least for a clean support of WebSockets and HTTP/2, a new API is necessary. At least for me, even if it isn't mandatory, to support easily bi-directional capabilities, it should be interesting to have an async API. May be a sync and an async API should coexist, like you have a little bit with python-ldap.

For now, WSGI spec doesn't move, and WSGI Web frameworks are blocked because are thought in the Request/Response model: it seems like an egg/chicken problem.

Instead to try to move in the political field of WSGI before implement something, maybe Gunicorn should propose something via a new worker with the new API, maybe under another name that WSGI to avoid to touch some sensibilities. If one of micro-frameworks like Bottle should implement that, it should be an interesting show case.

I imagine that you want to implement only a HTTP API, nevertheless, because WebSockets and HTTP/2 are bidirectional, it's may possible to have a similar API like Streams in AsyncIO: https://docs.python.org/3/library/asyncio-stream.html
And it should be possible to me to implement this API on the top of my multi-protocol worker.

**Comment by urbaniak** [comment]
I've done similar thing to gevent-websocket with aiohttp for py3k, it's just a separate worker class which sets the environ['wsgi.websocket'].

Here's the code - https://gist.github.com/urbaniak/3eccb06e8d5ac6c445f7

Have ben using that for last two months, it looks pretty stable.

**Comment by benoitc** [comment]
@GMLudo beeing bi-directionnal doesn't imply to use an asynchrnous library though. we can have a `recv` that could block until a message come, or just return if nothing came after a time and `send` can be non blocking. Afterwall a websocket is "just" a socket over the web.

Similarly we can have a recv_async that would receive asynchronously the message.

**Comment by tilgovi** [comment]
Here's the same in ws4py with 'ws4py.socket' in the environment. And here, again, https://github.com/Lawouach/WebSocket-for-Python/blob/master/ws4py/server/geventserver.py is `self.socket` or `environ['wsgi.input']`.

I think what's going on is that mostly we all just need to agree on where the socket is in the environment, no? Why is there so much variation here? Or am I misunderstanding something?

**Comment by tilgovi** [comment]
Is the first action here maybe that we need to ensure Gunicorn is exposing the socket is a consistent way across worker types? Or is it already?

The main thing I'm first worried about is that whatever auxiliary libraries users have for handling websockets that they don't have to vary their configuration or instantiation depending on the worker type.

**Comment by benoitc** [comment]
@tilgovi i think it's available for all the workers in the environ key `gunicorn.socket` :+1: 
https://github.com/benoitc/gunicorn/blob/master/examples/websocket/websocket.py#L45

and then you can tell to gunicorn to forgot that request: 
https://github.com/benoitc/gunicorn/blob/master/examples/websocket/websocket.py#L115

same for gevent:
https://github.com/benoitc/gunicorn/blob/master/examples/websocket/gevent_websocket.py#L44

**Comment by benoitc** [comment]
but not in the tornado and asyncio one :/ 

While it's ok to not support it in tornado we should make sure that such feature is available in the asyncio worker imo.

**Comment by GMLudo** [comment]
@benoitc you're right Benoit async isn't mandatory for websockets, however, I'm interested in to see macro-benchmarks on this particular use case, with a lot of permanent websockets AND without black-magic to automagically transform sync code to async via Gevent, because at the end, in fact, if you use that, you compare async code with async code, it's only explicit vs implicit that change ;-)

More seriously, at least to me, it's a wrong debate to oppose sync and async, like virtualization and physical servers or SQL and NoSQL: the "truth" is often in a mixin of several "opposite" techniques.

I think you have the right approach to support both, sync and async, and let Darwin to select the interesting tools for each use case in the long term.

**Comment by tilgovi** [comment]
Is it usable by sync worker? If so maybe we should relocate the constant.

I'll check if PyWSGI gevent worker exposes the same, and eventlet.

**Comment by benoitc** [comment]
@tilgovi i think that proposing an API that allows the application to upgrade the connection to a websocket and a way to retrieve/send messages to it would be good. While designing such approach we should also have in mind HTTP2.

**Comment by GMLudo** [comment]
> Is it usable by sync worker?

As usual, depends on your context: In this case, the traffic you have on your application.
In the case of classical stateless HTTP request/response, it isn't a big issue to be sync inside an handler. For a WebSocket, the context is different, but if you have few load, it isn't a big issue. The information I don't have where is the cursor: 10, 100, 1000 simultaneous WebSockets ?
However, if you have enough ressources/money, it's always possible to stack Web VMs and use an HAproxy behind to distribute the load.

**Comment by benoitc** [comment]
@tilgovi first one is in fact for eventlet. It's only working on the workers inheriting from the `AsyncWorker` class.

**Comment by tilgovi** [comment]
The `PyWSGIHandler` used by `GeventPyWSGIWorker` is setting "gunicorn.sock" instead of "gunicorn.socket". Is this just a mistake?

**Comment by benoitc** [comment]
@tilgovi it's a bug :)

**Comment by benoitc** [comment]
closing the issue.

1. gunicorn is actually exposing the socket but also handle wsgi.input_terminated
2. ASGI support and other features are planned.

**Comment by olawalejuwonm** [comment]
> closing the issue.
> 
> 1. gunicorn is actually exposing the socket but also handle wsgi.input_terminated
> 2. ASGI support and other features are planned.

Is it available now?
