### ISSUE TITLE
add lingering pool

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1025]
To solves #874 and #872 we should introduce a lingerpool as discussed in these issues. I propose the following design:
- in a linger pool all sockets are put in an event loop using the selector API 
- each time we come back in the accept loop we check if a socket is available for read in the event loop, if yes we then definitely close it using the shutdown method followed by the close method.

I think it could work, but will add an extra time when accepting a connection. Maybe we should maintain a thread? Or just put the linger pool inside the arbiter?

Also how do we handle the gevent and eventlet workers? We have little control on them using their server object ( I wonder if we shouldn't provide our own server impl at some point...) . Maybe we could ignore them for the next release?

Let me know what you think about that design anyway.

> This issue supersedes #874 and #872

**Comment by GMLudo** [comment]
What are the impacts of this feature for AsyncIO workers gaiohttp, aiohttp.web and API-Hour ?

I've no opinion about this problem, because to my knowledge, I've never observe this issue on my production with tcpdump.
It could be possible it's only with Nginx you have that ? I use only HAproxy for TLS behind my API-Hour daemons. Or maybe another manner to handle HTTP discussion by aiohttp.web.

It could be possible to disable this feature if necessary ?

**Comment by benoitc** [comment]
default lingering  settings may be enough on your system for your usage. It really depends. I can't reproduce it as well. Looking at different HTTP servers, it's apparently a common problem. The solution above should solve it. 

About making it optional that's a really good idea, and we could add a setting for it. Same for the lingering timeout I guess. I will propose a branch asap for it.

About asyncio, we have no way yet to handle it, directly at the moment in the current worker but @asvetlov will know maybe. It can be handled in the worker when you're about to close the connection socket. We could make the asyncpool asynchronous if needed.

**Comment by tilgovi** [comment]
Definitely this is behind a config switch to start, or can be turned off with one. No doubt.

@benoitc if we did this in the arbiter, I'm not sure how the worker could signal they are done. However, that would seem like the simplest thing to me. As long as none of the worker servers try to continue selecting on the sockets once they report they are "done" with them, this seems like it would work fine for all workers.

**Comment by benoitc** [comment]
@tilgovi yeah that would imply to add some kind of signalling system between the arbiter and the workers. Nothing fancy though, a pipe would be enough imo. 

We have 2 options anyway: 
- do a simple patch now and add lingering checking in the worker
- start to add simple signalling between the workers and the arbiter. bonus point it could help us to finally removed the temporary file...

**Comment by tilgovi** [comment]
I'm worried that we might need more signals in the future, but at the moment we would just need:

- I'm alive
- Here's a socket to add to the linger pool

That means we could get away with just piping integers, with -1 being the heartbeat.

**Comment by benoitc** [comment]
I described what could be the message system in an old presentation:  https://speakerdeck.com/benoitc/gunicorn-the-thundering-herd-and-other-concurrency-programming-challenges?slide=13

But we could start simple indeed. 

Should we do the lingering pool change in 19.4 or postpone it for next major release?

**Comment by GMLudo** [comment]
+1 for a simple approach.
For me, postpone it for next major release.

If it was my project and the alone user, I'll use Redis as shared data and communication between workers.

But I understand that you want to keep Gunicorn installable without any dependencies.

To me, our need to discuss between your processes is generic, it should be a library in pure Python easily embeddable in a Python project without dependencies, easily useable without Gunicorn.

However, instead to implement our own communication protocol, if I had the time, I should be tented to reimplement some parts of Redis protocol in pure Python, apparently, it isn't really complicated: http://jamesls.com/writing-redis-in-python-with-asyncio-part-1.html
With that, you should embed a Redis server easily as a coroutine in the Arbiter and workers connect as clients: It isn't an issue because you're Python 3 only for the next major release.
And for them who want to have more efficiency on production, they can use the standard redis-server.

In fact, with that, we have the butter (Redis) and the money of the butter (Don't need to setup Redis).

BTW, I use "Redis" as communication protocol in my previous paragraph, if you know another protocol with an implementation more efficient than Redis for a shared data mechanism, I'm really interested in, I'm not married with Redis, it's a layer easily changeable.

Certainly use SHM directly like PostgreSQL is more efficient than use Redis via UNIX socket, I don't know, however, a macro-benchmark should be interesting to be sure that in fact, on the big picture, this improvement change only few pixels about efficiency of the complete solution.

**Comment by benoitc** [comment]
redis wouldn't be efficient there. We are talking about sharing sockets
fds, lock informations and maybe more. This should be very fast and without
a txp ovehead. The design I have in mind is inspired from zmq and httpd in
openbsd.

- benoît

**Comment by GMLudo** [comment]
Ok, I'm interested in to test that. 
If it could be possible to workers to use that to discuss a little bit between workers, it should be interesting.

**Comment by benoitc** [comment]
closing the issue as won't do.
