### ISSUE TITLE
Gunicorn's settings - workers vs threads

### ISSUE THREAD

**Issue by jkozlowicz** [benoitc/gunicorn#1045]
Could someone clarify what workers and threads in gunicorn's settings are? The advised number of workers/threads in the docs is the same (with the same reasoning).

**Comment by jasich** [comment]
:+1:

**Comment by tilgovi** [comment]
Workers are the number of processes that get spawned. Threads are the number of threads in each process.

Threads is _only_ meaningful with the threaded worker. Every other worker type ignores that setting and runs one thread per process.

The advise and reasoning are the same because the effective concurrency is the same.

**Comment by nadermx** [comment]
So to just clarify you can run threads with workers?  Still having a bit of a issue understanding the abstraction.  

If I have a function with say 5 workers and 5 threads, that means I could have a lot of i/o waiting and have 5 cpu intense tasks running at the same time while waiting for that worker?

**Comment by heticor915** [comment]
Hi After reading the documentation it is not pretty clear for me. What would be the number of workers to run normally .

**Comment by heticor915** [comment]
Hi everybody, after searching for a while I just found  a cool[ tutorial](http://michal.karzynski.pl/blog/2013/06/09/django-nginx-gunicorn-virtualenv-supervisor/) for Setting up Django with Nginx, Gunicorn, virtualenv,and  supervisor.  maybe this could help:

> 
As a rule-of-thumb set the **--workers (NUM_WORKERS)** according to the following formula: _**2 * CPUs + 1.**_ The idea being, that at any given time half of your workers will be busy doing I/O. For a single CPU machine it would give you 3.

**Comment by tuukkamustonen** [comment]
> Threads is only meaningful with the threaded worker. Every other worker type ignores that setting and runs one thread per process.

Might make sense to add this to docs for `--threads` option.

Also should clarify that *threaded worker* refers to *gthread* worker in specific (*gthread* worker is described under "AsyncIO workers" section in http://docs.gunicorn.org/en/stable/design.html because it works on a main loop). Just stating this may be a bit confusing.

Also, does `--workers` have any effect with async(IO) workers? I would assume no, or at least user should not increase them?

**Comment by tilgovi** [comment]
@tuukkamustonen `--workers` affects every type of worker.

@heticor915 the best thing is to test with your specific workload. As far as I know, the `CPUs * 2 + 1` formula comes from the idea that while one connection is doing I/O another can be using the CPU, with the `+1` for flexibility at the cost of maybe some scheduling. If we take the threaded worker, we have `number of threads * number of workers` connections handled at once. This product should be, again, likely about `CPUs * 2 + 1`. Deciding which is better (threads or workers) is probably a trade-off between the overhead of the GIL (threads) and the memory overhead of starting new processes that each need to load the application (workers). Using `--preload` can eliminate some of the memory overhead of workers. However, I cannot stress enough: *it is best to test*.

Start with sync workers and `CPUs * 2 + 1`. Choose a different worker model if you have I/O that might block on external resources (like making API calls to third parties). Adjust if you have memory pressure or encounter performance problems and choose what works best by testing. Choose between eventlet, gevent, tornado, etc based on what you're familiar with and trust, as well as compatibility with libraries you use. Choose sync or threaded or asyncio (Python 3) for most basic usage.

**Comment by tuukkamustonen** [comment]
@tilgovi Ah, right. I guess with async workers you should match the amount of workers with the amount of CPU cores (due to GIL) and there shouldn't be reason go over that?

**Comment by prkamath** [comment]
@tilgovi I am wondering why you said that the setting of --threads is ignored by Sync worker type. I believe it is taken into account. To start off the worker might create only one thread, but if the requests pile on, it will create more threads till it reaches the max count as indicated by --threads. If it does not do this then how will it handle workloads that do plain IO. With a single thread and a single worker you would be able to handle only one request at a time. But if we have 4 threads in the singular Sync worker, we can handle 4 requests at a time.

**Comment by tilgovi** [comment]
The threads option is a shorthand for selecting the threaded worker. It's "synchronous" in that each thread will block on some calls like socket reads (unlike the asynchronous workers), but it is not the sync worker, the default worker class. Using `-k gthread` (I think this is how to select the threaded worker, but I'm not at my computer) is implied by `--threads`.

**Comment by benoitc** [comment]
@tuukkamustonen you may want to go over the number of cores to increase the parallelism outside of the Gil. The number advised is 2N+1 as @tilgovi said. Also good point the the gthread worker should probably be put in the Async section . I think the only reason it's there is because we're using the same event loop and futures code. 

@tilgovi `--threads` imply the launch of the `gthread` indeed. The gthread is conceptually the same as a sync worker except that we have another level of concurrency on top of a worker, so maybe we shouldn't even describe the existence of the gthread worker?

**Comment by tilgovi** [comment]
Yes, it might be good to eliminate the threaded worker distinction in the documentation, or clarify it.

**Comment by RyPeck** [comment]
@tilgovi @benoitc from my reading of the source code it was news to me that the `--threads` configuration option is only used by the `gthread` worker type.

Perhaps the application should print a warning when using configuration options that are ignored by the selected worker class? 

@benoitc so is `gthread` not an async worker? Or is it an asyncio worker? The worker class doesn't inherit from `AsyncWorker` like `gevent` and `geventlet`.

**Comment by benoitc** [comment]
@RyPeck `--threads` is an option to accept on more than one threads for sync workers. The gthread is neither a sync nor an async worker. It's a worker that handle different strategy to play around the GIL to handle the concurrency . The gthread worker exists outside the sync worker to isolate the concerns.


The question is if we should be explicit in setting the worker (ie forcing the user to use `-k gthread` or not. Or on the contrary never mention this worker, and keep it hidden for the end-user while documenting more the `-threads` option. What do you think?

**Comment by tuukkamustonen** [comment]
@benoitc Why the need to go over the amount of nodes with async worker? Async worker can utilize the available CPU by serving new requests when the loop is waiting for IO. I would assume N workers on N cores should be able to utilize 100% CPU? Of course, going 2N+1 is ok as well, but it shouldn't be needed. On sync workers, something like 2N+1 makes sense yeah, because if all workers (and threads) are waiting for IO, then no new requests are served even though there would be CPU available.

I have never used async workers but this is how I've understood it. Maybe I got it all wrong?

**Comment by benoitc** [comment]
even if the situation is better with an async worker you still have the
gil. so using as many worker + 1 as many cpu you have allows you to
increase the number of request you can handle in parallel .

**Comment by DanielStevenLewis** [comment]
@tuukkamustonen @benoitc it's unclear to me from your conversation what the recommended number of async workers is. Could you please clarify? 

Also, does that number still make sense if gunicorn and the db are running on the same server?

**Comment by benoitc** [comment]
@danielquinn using 2 N+ 1 workers will allows you to accept 2+1 sockets in // (at least in // OS system processes.

For the second question, these are different things. The number of workers is to allows you to accept concurrently the connections.

**Comment by LoveUrfuNo** [comment]
Hello, help me pls anyone. I have a chat bot written in python django and deployed with gunicorn. I started 12 workers on cpu with 2 cores. More than 12 I do not run, because the documentation is not recommended, but my cpu is loaded 7 percent maximum. Why I can not run 20 processes and more? Maybe I need run worker with multiple threads? I tried, but bot send many responce on one request. How can I start using all the resource of the processor? Maybe it's worth deploying the application to a different technology instead of gunicorn? Gunicorn i'm running so: nohup gunicorn --workers=12 --max-requests=5000 --bind 127.0.0.1:8000 exgirlbot.wsgi:application & . Thank you.

**Comment by tilgovi** [comment]
There are lots of reasons your bot might not use all the cores. It's not possible to diagnose this for you without a lot more information. Please take some time to benchmark your application and figure out where the bottlenecks are.

Let's keep this issue about the differences between the workers and how best to communicate those differences, such as in the documentation.

**Comment by AlJohri** [comment]
I'm still very unclear on how threads work with gunicorn. Particularly I'm confused about how (1) threads interact with processes and (2) how threads interact with spawning new threads in the app.

I have two main questions:

1) It is unclear that if I want to use multiple threads and multiple processes what worker_class should be set to. Should worker_class be `sync` or `gthread`. From the descriptions above, it seems as though if I set `--workers=3 --threads=2` I would have 3 processes with 2 workers. But if the worker_class is gthread, does `workers` still mean processes? My interpretation would be that worker is of type worker_class but it seems as though _worker is always a process_ regardless of worker class?

At the very least, I think `gthread` needs to be mentioned at least once under the `Sync Workers` section here http://docs.gunicorn.org/en/latest/design.html.

2) It's unclear how the `preload` option works for threads and especially **how this interacts with other threads your app is already using**. For example, I would like to spawn a thread in the background that does some expensive IO every 15 seconds and sets a common data structure. The app itself just needs to serve up the common data structure. I would like to use threads so I can share this memory. My understanding thus far is when using `--worker-class gthread --threads 5` without the preload option, **each worker thread will spawn a new thread** to perform the IO and the **common data structure is not shared**. When running with the preload option, the module level common data structure is shared but it now seems to be static. The spawned thread is unable to change the data?

This is the example code I'm working with to better understand threading with gunicorn: https://stackoverflow.com/a/22900255

This is my invocation without the preload option:

```
gunicorn \
	-b 0.0.0.0:5000 \
	--worker-class gthread \
	--threads 5 \
	--access-logfile - \
	app:app
```

**Comment by AlJohri** [comment]
I made a sample app to elaborate the second question: https://github.com/AlJohri/flask-threading-examples/tree/master/example1

It spawns a background thread and changes a common data structure. I was hoping to either share the data structure or get some clarity on what is happening.

**Comment by tilgovi** [comment]
> But if the worker_class is gthread, does workers still mean processes?

Yes. Workers always means processes.

> My interpretation would be that worker is of type worker_class but it seems as though worker is always a process regardless of worker class?

Correct.

> At the very least, I think gthread needs to be mentioned at least once under the `Sync Workers` section

I have recognized that this part of the documentation could use work:

> Yes, it might be good to eliminate the threaded worker distinction in the documentation, or clarify it.

It would be wonderful if someone reading this issue could submit a PR. It is sometimes better to write this sort of documentation without all the knowledge of a maintainer; if I write it I am likely to take some terminology for granted.

> My understanding thus far is when using `--worker-class gthread --threads 5` without the preload option, *each worker thread will spawn a new thread* to perform the IO and *the common data structure is not shared*. When running with the preload option, the module level common data structure is shared but it now seems to be static. The spawned thread is unable to change the data?

With the preload option, your application is loaded once. Without the preload option, your application is loaded once in each worker. You can launch your thread when your application loads and get one background thread per worker, or you can launch a thread in a `post_fork` hook if you want one thread per worker _even with preloading_.

Without preloading, your workers will definitely not share any data between them unless you use external storage (filesystem, database, network accessible cache, etc).

With or without the preload option you will end up with one background thread in each worker because when a process forks it forks all its threads. Whether the threads are created before the fork or after does not matter. In both cases the processes are independent once forked and do not share data structures. If you populate the data at module load time, that initial data will be visible to every worker. Future modifications will not be because they happen in separate processes. To share memory between processes (workers) you need to use a construct for explicitly sharing memory (`/dev/shm`, filesystem, network cache, db, etc).

**Comment by AlJohri** [comment]
@tilgovi that was SUPER helpful, thank you!

> With or without the preload option you will end up with one background thread in each worker because when a process forks it forks all its threads.

That makes sense.

> Whether the threads are created before the fork or after does not matter. In both cases the processes are independent once forked and do not share data structures. 

So at a minimum, even in sync mode, there are always going to be at least two processes? Is there an option to prevent forking and run the threads / serve directly from a single process? I believe uWSGI has a `--master=false` (which I understand is highly discouraged to be used).

**Comment by jamadden** [comment]
> You can launch your thread when your application loads and get one background thread per worker, 

> With or without the preload option you will end up with one background thread in each worker because when a process forks it forks all its threads.

I am really pretty sure that threads do not survive a fork. After a fork, the only thread still running is the thread that called fork. All other threads silently die (this is how you can end up with deadlocks if you fork while a different thread is holding a lock; that thread will never run again to release the lock).

This program demonstrates that other threads do not continue after a fork in the child:
```python
import threading
import os
import time

pid = os.getpid()

print("The parent pid is", pid)


run_thread = True
exec_count = 0

def thread_func():
    global exec_count
    while run_thread:
        exec_count += 1
        if os.getpid() == pid:
            print("I am running in the parent")
        else:
            print("I am running in the child")

        time.sleep(1)

t = threading.Thread(target=thread_func)
t.start()
time.sleep(2) # Should print twice

new_pid = os.fork()
if new_pid:
    # I am the parent
    print("The parent is still running; stopping it")
    run_thread = False
    t.join()
    time.sleep(10)
else:
    print("I am the child. Am I running? Should the thread run?", run_thread)
    exec_count = 0
    # Lets wait and see
    time.sleep(10)
    print("Did we run in the child?", exec_count)
```

Sample output:
```
$ python /tmp/test.py
The parent pid is 43181
I am running in the parent
I am running in the parent
The parent is still running; stopping it
I am the child. Am I running? Should the thread run? True
Did we run in the child? 0
```

**Comment by tilgovi** [comment]
> Is there an option to prevent forking and run the threads / serve directly from a single process?

There is no such option currently.

**Comment by tilgovi** [comment]
I stand corrected regarding forks and threads. Thank you @jamadden!

@AlJohri it sounds like you should not use the preload option if you are running a background thread when your module is imported and depending on it to update shared data. You could, however, use a `post_fork()` hook to start your thread. Then, even with preload, you should get one additional thread per worker.

**Comment by benoitc** [comment]
That's correct threads will not survive to their parent death.  I'm thinking we could add a warning when using preload and anything but a sync worker, thoughts?

**Comment by benoitc** [comment]
closing the issue . no activiy since awhile.

**Comment by RomainWilbert** [comment]
Is the app.run(threaded=True) really needed when using gunicorn gthread worker ?

**Comment by colidyre** [comment]
> Is the app.run(threaded=True) really needed when using gunicorn gthread worker ?

I think you are referring to the Flask server, which can be started via `app.run()`. This delegates arguments to the Werkzeug server, so you don't need Gunicorn at all to start your app. Gunicorn is simply a different way to start your application as a web application.

This is also a bit of an understatement. The Flask server (actually the Werkzeug server) is only for development purposes. Gunicorn can gain a lot of performance in a productive environment (instead of using the Werkzeug server (which is not recommended, though), for example).

The question in this issue aims to get an overview of what settings can be made in Gunicorn and what they mean (mainly workers and threads) and if this means a performance gain.

Again:
> Is the app.run(threaded=True) really needed when using gunicorn gthread worker ?

To answer the question: No, this is not necessary, because no `app.run()` is executed at all in this case -- no matter if threaded (default since Flask version 1.0) or not.

I hope I could shed some light on the confusion.

**Comment by Frikster** [comment]
I found this [SO post](https://stackoverflow.com/a/41696500/2734863) quite enlightening when considering the trade-offs of threads vs workers. For me it was more useful in helping me see the distinction between the two than the answers I read here.
