### ISSUE TITLE
19.3.0: python-2.7.10 incompatibility

### ISSUE THREAD

**Issue by 0-wiz-0** [benoitc/gunicorn#1108]
19.3.0 does not fully compile with python-2.7.10, one file fails with:
````
   File "/usr/pkg/lib/python2.7/site-packages/gunicorn/workers/_gaiohttp.py", line 68
     yield from self.wsgi.close()
              ^
 SyntaxError: invalid syntax
````
The code is still there in github version as of today, now it's just line 78 of that file:
https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/_gaiohttp.py#L78

**Comment by benoitc** [comment]
Do you mean that this file is not built? Then it's expected, but let me know otherwise.

**Comment by 0-wiz-0** [comment]
The build tries to make .pyc/.pyo for this file and fails.
The .py file is still installed, however (and will probably fail at runtime if it's ever used).

**Comment by benoitc** [comment]
Thanks for the details.

Anyway this error harmless and expected like reported many time before :) It can safely be ignored. To answer to your concern the file will never be used if you're under python 2.x.  Also it should not be reported in recent versions of pip but @berkerpeksag will confirm that.

Anyway closing this issue as WONT FIX since there is nothing we can do apart extracting any code specific to python 3 code from the core.
