### ISSUE TITLE
Round robin scheduling of websocket requests to the workers

### ISSUE THREAD

**Issue by scheler** [benoitc/gunicorn#1130]
Gunicorn design says:

Gunicorn relies on the operating system to provide all of the load balancing
when handling requests. 

With WebSocket requests, this is resulting in uneven load balancing of requests to the workers. that is, some workers handle lot more WebSocket connections than others. 

Fair scheduling based on the current CPU usage of the workers may not be fair for websocket apps, as unlike short lived http requests, websocket requests need to be fair across workers over a longer period of time. Can we get support for alternate forms of scheduling the requests to the workers?

**Comment by tilgovi** [comment]
That would be a large change. Right now, gunicorn has no knowledge or ability to schedule requests to workers. All workers simply call `accept` on the socket and the operating system chooses one.

I wouldn't say it's out of the question, but this properly needs a champion willing to implement it and submit a PR.

**Comment by GMLudo** [comment]
@scheler: if you really need that on production, install an haproxy and use it to distribute load like you want.
In each worker, open a different listening socket to permit haproxy to discuss privately to each worker.

**Comment by scheler** [comment]
@GMLudo do you have an example for 'opening a different listening socket in a worker'?

**Comment by scheler** [comment]
@GMLudo Also, scaling the number of workers is not going to be as straightforward as just specifying the number of workers, like in gunicorn. haproxy/nginx would need to be reconfigured each time number of workers change. thoughts?

**Comment by GMLudo** [comment]
I've a daemon with API-Hour + asyncio. 
With asyncio, it's pretty easy to open a socket to do that. What's the framework you use for websockets? 
Even if I'm not a big fan to have dynamic number of workers, it isn't really an issue, at least for haproxy : you have an Unix socket to control and change the configuration on the fly.

**Comment by scheler** [comment]
I am using gevent-websocket.

**Comment by benoitc** [comment]
@scheler  So far if you're listening on a specific port, the fastest worker to answer would handle the connection, it should do the trick most of the time.

I am working on a simple and pure python library working like [imsg](http://www.openbsd.org/cgi-bin/man.cgi/OpenBSD-current/man3/ibuf_add.3?query=imsg%5fread&sec=3) under OpenBSD that will improve the way messages are passed between processes.  It won't be available until the end  of the week. In fact I decided to re-attributes some cycles to write the latest bits  this week. Then it will be introduced inside Gunicorn.

Waiting that rather than implementing a "locking" solution like suggested above, maybe a simple hack would be changing the priority of the workers (using nice and renice) when they receive a connection. It will instruct the system which worker to assign a connection in priority. You can do it using an external process watching the load, or just by switching the priority of the worker in an hook once the connection is accepted. I would be interested in any feedback about that solution :)

**Comment by scheler** [comment]
@benoitc wouldn't nice affect the process' overall behaviour and not just lower its chance to accepting a new connection?

**Comment by tilgovi** [comment]
I also don't know that nice would even accomplish this. I don't know that process priority is considered when deciding which thread to wake from `accept()`.

**Comment by scheler** [comment]
I noticed gunicorn master can listen on multiple addresses at once, and all workers currently accept connections from all listeners (ref: https://github.com/benoitc/gunicorn/blob/master/gunicorn/arbiter.py#L498).  Do you see any issue if we distribute the listeners to the workers here?

It will tricky to assign listeners as workers are removed and new ones are added, but anything other than that?

**Comment by GMLudo** [comment]
Maybe we should follow Nginx idea: https://www.nginx.com/blog/socket-sharding-nginx-release-1-9-1/
SO_REUSEPORT option seems to be a good improvement.
It means that we need a config option to enable that, you don't need to open socket in master, but directly in workers.
To my experience, you shouldn't try too much to balance charge with business logic: The time to take decision to load balance each request couldn't compense the better balance effect, as usual, need to be measured.

*In Benchmarkos Veritas* ;-)

**Comment by benoitc** [comment]
@GMLudo so you specifically means adding socket sharding there? I think we need a new feature ticket for it. Also patch are accepted as usual ;)

**Comment by GMLudo** [comment]
@benoitc I'm overloaded right now, I've added this idea in my todo-list.
If somebody else has time to do that, be my guest.

**Comment by benoitc** [comment]
closing issue.  I personally think that round robin will happen naturally since the connection won't be accepted at the same worker.

@GMLudo if you can come with a design proposal or patch in a separate ticket it would help to progress on the idea.
