### ISSUE TITLE
gunicorn+gevent/eventlet+flask+send_file, cStringIO?

### ISSUE THREAD

**Issue by yijunjun** [benoitc/gunicorn#1160]
in flask:
@app.route("/test")
def test():
import cStringIO
output = cStringIO.StringIO()
...
return send_file(output)

**Comment by benoitc** [comment]
@yijunjun what is the issue?

**Comment by yijunjun** [comment]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 130, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/lib/python2.7/site-packages/gunicorn/workers/sync.py", line 174, in handle_request
    resp.write_file(respiter)
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 394, in write_file
    if not self.sendfile(respiter):
  File "/usr/lib/python2.7/site-packages/gunicorn/http/wsgi.py", line 357, in sendfile
    fileno = respiter.filelike.fileno()
AttributeError: 'cStringIO.StringO' object has no attribute 'fileno'

**Comment by benoitc** [comment]
@tilgovi ping

The issue comes from the removal of the fileobject testing:
https://github.com/benoitc/gunicorn/commit/18d2b92146592b3f5370fb1d964ce91a416c693e#diff-0b90f794c3e9742c45bf484505e3db8dL520

I am really not sure we shouldn't be strict there and only accept fileobjects providing a `fileno` method or attribute

@yijunjun in the mean time why do you want to use sendfile here? Why not simply returning an iterator (the StringIO would be enough). Gunicorn will stream it.

**Comment by yijunjun** [comment]
I can solve this problem.I just want to report a problem.Thank you for your answer.

**Comment by pudo** [comment]
Got the same issue. Wonder if it can't be caught more softly.

**Comment by volnt** [comment]
Got the same problem here too. How can this be avoided ?

**Comment by tilgovi** [comment]
We can catch the exception. I should be able to get to this over the weekend if no one else can. Closing any other issues on the milestone will help get this released faster.

**Comment by benoitc** [comment]
@tilgovi sounds like a plan :)
