### ISSUE TITLE
 Improper "unquoting"

### ISSUE THREAD

**Issue by jcea** [benoitc/gunicorn#1161]
I am requesting this URL to my WSGI application: "http://127.0.0.1:8080/buffy/Test%20%C3%A1%20%C3%B3".

What I am getting in PATH_INFO is: "/buffy/Test Ã¡ Ã³". This have two problems:

1. The string is "unquoted". I would expect to get it "as" I send it. That is what other WSGI servers do.

2.  The unquoted is literal, not doing the right utf-8 translation. The right unquoting would be "/buffy/Test á ó".

Currently I am running my WSGI with the following adapter in order to circumvent both issues:

```
def adaptador(environ, start_response) :
    from urllib.parse import quote

    path_info = quote(environ['PATH_INFO'].encode('latin-1').decode('utf-8'))
    environ['PATH_INFO'] = path_info
    return wsgi.application(environ, start_response)

[...]

StandaloneApplication(adaptador, options).run()
```

**Comment by tilgovi** [comment]
Hmm, are you sure your first point is accurate? Looking at the section entitled "URL Reconstruction" in the [wsgi spec](https://www.python.org/dev/peps/pep-3333/#url-reconstruction) it seems as though the original request URL is supposed to be retrieved as per your adapter. The environment stores the unquoted version.

**Comment by benoitc** [comment]
Thanks for the ticket! 

Not sure what other server do, but PATH_INFO is supposed to be unquoted according to the spec like @tilgovi said.  (This behaviour is also in place since a very long time)

For your information if you want to skip the need to reconstruct the URI you can use the non standard `RAW_URI` environ setting to retrieve the URI like it was received by the server.

closing as "WONT FIX".
