### ISSUE TITLE
LoopExit from gevent on application startup

### ISSUE THREAD

**Issue by GarrettHeel** [benoitc/gunicorn#1192]
I get a `LoopExit: ('This operation would block forever'...` on the `t.get().ok` from gevent for the below code block. This does **not** happen on `gevent==1.0.2`, but does on `gevent>=1.1b1`. It appears to be related to forking, since it doesn't happen when adding `--preload`.

I've also tested the same app with uWSGI (`uwsgi --gevent 100 --lazy-apps ...`) and was unable to recreate the error, including with and without preloading. 

```python
# gunicorn -k gevent gunicorn_issue:app

import gevent
from flask import Flask
import requests

app = Flask(__name__)

def fn():
  return requests.get('http://httpbin.org')

t = gevent.spawn(fn)
v = t.get().ok  # this causes gevent loopexit

@app.route('/')
def root():
  # v = t.get().ok  # this does _not_ cause loop exit
  return 'Hi'
```

**Environment**

Python 2.7.11

```
gunicorn==19.4.5
gevent==1.1rc3
Flask==0.10.1
requests==2.9.1
```

**Comment by jamadden** [comment]
This is an unfortunate result of the fix for gevent/gevent#108. It can be worked around by adding `builtins=False` to the call to `gevent.monkey.patch_all` in `gunicorn.workers.ggevent`---but of course that reintroduces the original problem. 

Alternately, because using the gevent blocking API at module scope (import time) is tricky (it's easy to get into this situation in various ways if you do), if you can structure your code to *not* do that (i.e., delay waiting on the greenlet as the comment notes) then you'll be immune to this particular type of problem.

Other than that, I don't have a solution at this time.

**Comment by jamadden** [comment]
Specifically what's going on here is that this file is being imported and `requests.get` *also* wants to import things. The import of this file holds the import lock, so the background greenlet for `requests.get` blocks to acquire the import lock. When this file, which is the main greenlet, tries to block on the background greenlet, not only do we deadlock on the import lock, but there are no other greenlets that are eligible to run: hence, LoopExit.

**Comment by GarrettHeel** [comment]
Fair enough, I'll look into your solutions to get around this somehow for now. 
Thanks for your help @jamadden!

**Comment by jamadden** [comment]
For reference, if you do the same thing with native threads, the process hangs (deadlocks on the cPython import lock).
