### ISSUE TITLE
chunked encoding bug with latest version of django.

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1264]
Following the discussing on #605 :
https://github.com/benoitc/gunicorn/issues/605#issuecomment-219228942

Django doesn't handle anymore chunked encoded requests. Not sure how to fix it yet.

**Comment by benoitc** [comment]
cc @jezdez maybe you know if there have been some discussions about it?

**Comment by benoitc** [comment]
ok I'm not sure what to do with this solution, maybe we should just force the usage of content-length for frameworks that don't handle HTTP 1.1 ? cc @tilgovi @berkerpeksag

**Comment by berkerpeksag** [comment]
If I remember correctly, Django handles HTTP 1.1. The lines you mentioned in https://github.com/benoitc/gunicorn/issues/605#issuecomment-219228942 haven't changed since 5 years and the OP's Django version is a little bit old. I haven't read the whole discussion in #605 and tried the [test project](https://github.com/genxstylez/test_chunked_upload) yet so I might be missing something here. Perhaps @timgraham or @claudep can chime in.

**Comment by claudep** [comment]
I don't remember anything about Django supporting chunked transfer encoding at the request side. It might well be a missing feature in Django.

**Comment by timgraham** [comment]
I don't know much about the specifics, but a quick search indicates "This is a not a Django issue. It is a limitation of the WSGI specification itself in as much as the WSGI specification prohibits use of chunked request content by requiring a CONTENT_LENGTH value for request." -Graham Dumpleton

http://stackoverflow.com/a/12091479

**Comment by benoitc** [comment]
i know what the spec says. But some frameworks allow to bypass this rule.
It also used to work with oldest versions of django. and for sure it won't
be removed fr gunicorn.

Anyway like i says we have limited options since i've never been answered
on that topic.so i propose to introduce a --strict option that would
default to true for django. strict would meanbin this case to return a 411
error. thoughts?

**Comment by benoitc** [comment]
no feedback given. closing the issue.
