### ISSUE TITLE
workers registration API

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1278]
Revisiting #1118.  I understand the need to register a unique worker id/ref, so you can use it in another process or your application for any purpose. But I don't think the current implementation respects the gunicorn design trying to detect a change based on the number of workers. We already know when a worker die. This is what is triggering the spawn events. We have already the following properties that can be used:
- A worker is identified by its PID and supervised the arbiter.
- The worker age is unique across worker and only incremented

So I think we need to introduce an API for it, allowing a hook to register a worker.

I propose the following:

``` python
gunicorn.register(Name, Pid)
gunicorn.unregister(Name, Pid)
gunicorn.whereis(Name)
```

A Pid should only be a supervised process in Gunicorn. Thoughts?

**Comment by yli-cpr** [comment]
The problem with age is it keeps increasing. In my case, I need a unique worker index that is in fixed range, so that I can allocate resources like log files for every worker. If I use `worker_age % num_workers`, there is a chance the ids conflict. So I am using the solution of prefork/postfork hooks. But this will assume that:

1. pre_fork() is only called from one thread in master process.
2. worker will become alive if everything is OK, before next call to pre_fork.

Is it safe to always assume they are true?

**Comment by tilgovi** [comment]
1. yes
2. what do you mean by alive?

**Comment by yli-cpr** [comment]
@tilgovi Thanks. by alive, I mean the Worker object's `alive` attribute. I assume it is `True` before being added to `server.WORKERS` and is `False` before being removed from `server.WORKERS`

**Comment by tilgovi** [comment]
`alive` is set to `True` in the worker constructor, so it should be marked alive immediately.

**Comment by yli-cpr** [comment]
@tilgovi Yes. My real question is if it is safe to assume this. Can this behavior change in foreseeable future?

**Comment by tilgovi** [comment]
I cannot say. It's part of the public API of the worker to have an alive attribute, but it's not really documented. In practice, we're pretty conservative about breaking behavior, and I think that's the sort of thing we would call out in a changelog.

**Comment by yli-cpr** [comment]
Thanks
