### ISSUE TITLE
SyntaxError?

### ISSUE THREAD

**Issue by v-hunt** [benoitc/gunicorn#1285]
I'm sorry, but I've got SyntaxError when installing Gunicorn via pip:

```
$ sudo pip install gunicorn

Downloading/unpacking gunicorn
  Downloading gunicorn-19.6.0-py2.py3-none-any.whl (114kB): 114kB downloaded
Installing collected packages: gunicorn
Compiling /tmp/pip_build_root/gunicorn/gunicorn/workers/_gaiohttp.py ...
  File "/tmp/pip_build_root/gunicorn/gunicorn/workers/_gaiohttp.py", line 84
    yield from self.wsgi.close()
             ^
SyntaxError: invalid syntax

Successfully installed gunicorn
Cleaning up...
```

**Comment by jamadden** [comment]
As with many projects that support both Python 2 and 3 from a single code base, that "error" can be expected during installs. (Here it looks like you were installing on Python 2.). This is because pip compiles all code to bytecode even if it's not appropriate for the running Python version. It can safely be ignored.

**Comment by berkerpeksag** [comment]
The exception is completely harmless and it has been fixed in pip a while ago. Please upgrade your pip. Thanks!
