### ISSUE TITLE
Printing access log to standard output

### ISSUE THREAD

**Issue by suriya** [benoitc/gunicorn#1293]
I apologize if what I am saying is wrong.

As far as I can tell, I don't see any easy way to print access logs to `stdout`. I see issue #1184. However, the fix does not seem to work. Invoking `gunicorn` without any arguments does no access logging. Invoking `gunicorn --access-log -` sends log messages to standard error (with gunicorn 19.6.0).

I someone could let me know how to get error messages logged to standard error and access logs to standard output, I'd appreciate it.

**Comment by tilgovi** [comment]
It does seem as thought `--access-log -` should probably mean stdout.

**Comment by benoitc** [comment]
It should be `gunicorn --access-log=-`. In theory it should be redireted to stdout:

https://github.com/benoitc/gunicorn/blob/master/gunicorn/glogging.py#L61-L77

If not, I will check what's missing.

**Comment by berkerpeksag** [comment]
Yes, the `gunicorn.access` logger should print to `sys.stdout`: https://github.com/benoitc/gunicorn/blame/master/gunicorn/glogging.py#L72 I think documentation is outdated: http://docs.gunicorn.org/en/stable/settings.html#accesslog

**Comment by tilgovi** [comment]
The documentation is not out of date, but the behavior seems a little broken. From the `CONFIG_DEFAULTS` that you link to, @berkerpeksag, it seems as though the _intention_ is for access log to go to stdout. However, that is the default configuration that the `--log-config` setting merges into.

Without `--log-config`, the default for accesslog is `None` (from config.py) and so no handler is set up for the access log: https://github.com/benoitc/gunicorn/blob/master/gunicorn/glogging.py#L213

With `--access-log -`, we might expect to get stdout. The documentation correctly states that it means `stderr`, because that's the default for a `StreamHandler` as created by `Logger._set_handler`: https://docs.python.org/2/library/logging.handlers.html#logging.StreamHandler

**Comment by tilgovi** [comment]
I propose we change the handling of `-` for the access log setting to mean `stdout`.

**Comment by benoitc** [comment]
fixed in df84d3d8fe6b2425f35d725a6c8259908672f35a . It was already defaulting to stdout by using the config file btw.

**Comment by suriya** [comment]
@benoitc Works as expected. Thank you so much!
