### ISSUE TITLE
Logging continues to old file after kill -USR1

### ISSUE THREAD

**Issue by shturman** [benoitc/gunicorn#1317]
Steps to reproduce with gunicorn 19.6.0:
1. set accesslog = "path/to/access/log"
2. move file "mv path/to/access/log path/to/access/log2"
3. kill -USR1 pid
4. empty file path/to/access/log created but access log stream goes to path/to/access/log2

I'm using Python 3.5.2
Ubuntu xenial 16.04
Worker: [GunicornUVLoopWebWorker](https://github.com/KeepSafe/aiohttp/blob/master/aiohttp/worker.py) from aiohttp.

**Comment by tilgovi** [comment]
Does this happen with other worker types?

**Comment by andrew-grasso** [comment]
I'm seeing the same thing with the default (sync?) worker type.
gunicorn 19.6.0
Python 2.7.6
Ubuntu Trusty 14.04

I'm using 4 workers, and using the same process as @shturman I see that some of the workers continue to use the old log file, while others move on to using the new one. I'm able to get them to load the new file by issuing a HUP instead of USR1 which closes all workers and re spawns them.

**Comment by jorgehatccrma** [comment]
We also see the same behavior using `logging.handlers.RotatingFileHandler` with default workers.

**Comment by kell18** [comment]
Hi! 
Is there any plans to fix this bug?
Thanks.

**Comment by benoitc** [comment]
not reproduced.
