### ISSUE TITLE
Support separate cookies to be logged in the access log

### ISSUE THREAD

**Issue by mindojo-victor** [benoitc/gunicorn#1321]
[Access log format setting](http://docs.gunicorn.org/en/stable/settings.html#access-log-format) allows logging request headers in the log file:

> `{Header}i`    request header
> `{Header}o`   response header

Nginx allows to [track a cookie value in the logging file](http://stackoverflow.com/questions/26128412/how-to-extract-some-value-from-cookie-in-nginx).

It would be nice to have the same in Gunicorn, because logging the whole `Cookie` header is not an option -- sometimes it's huge.

**Comment by benoitc** [comment]
well it's also huge to parse... we should probably handle the logs outside the main thread if we want to add such features. @berkerpeksag @tilgovi thoughts?

**Comment by benoitc** [comment]
bump

**Comment by tilgovi** [comment]
It's a feature request, which is okay, but I don't know if we need to keep it open. Do we have a good process for feature requests? It can become quite noisy to have lots of feature requests open with no PRs.

I might support a PR for this feature. The user can enable it with knowledge of the performance impact.

On the other hand, NGINX can forward requests and serve static content and do other things where the user _needs_ NGINX to log the cookie because there is no other way to see it. Gunicorn is always running a Python application that is probably easily modified to log the cookie from the WSGI application side. I think the feature is probably unnecessary for Gunicorn.

I vote to close the issue. If someone really needs it they can make a PR and we can consider it.
