### ISSUE TITLE
Gunicorn conf file, environment variables syntax

### ISSUE THREAD

**Issue by leonardbinet** [benoitc/gunicorn#1472]
Hello,
In the documentation, it is written that there is no special syntax for config, but I don't understand how to use the env parameter to pass multiple values. 

Should I use a dictionary to pass multiple values?

For instance I would like to pass environment variables in gunicorn processes, my `gunicorn_config.py` file is:
```
bind = "127.0.0.1:8887"
log_file = "path/to/logs/gunicorn_logs.txt"
workers = 3

# Environment variables
env = {
    "DJANGO_SECRET_KEY": "something",
    "OTHER_SECRET": "something_else"
    }
```

But it doesn't work. Is my syntax right?
Thanks in advance

**Comment by leonardbinet** [comment]
Ok, in found it:
```
# Environment variables
raw_env = [
    "DJANGO_SECRET_KEY=something",
    "OTHER_SECRET=something_else"
    ]
```

**Comment by benoitc** [comment]
ok, closing the issue since you found it :)

**Comment by alexprengere** [comment]
Hello, I was stuck on this exact issue today, because I used the [example](https://github.com/benoitc/gunicorn/blob/master/examples/example_config.py) which is not up to date with the [latest docs](https://gunicorn-docs.readthedocs.io/en/18.0/configure.html). Thanks to this issue, I could find `raw_env` though 😉

**Comment by berkerpeksag** [comment]
@alexprengere I've just added an example to `examples/example_config.py` in https://github.com/benoitc/gunicorn/commit/01a1c7ca9a76d14a707b2946192ca7278247c2ce.
