### ISSUE TITLE
add auto-reload option

### ISSUE THREAD

**Issue by aljosa** [benoitc/gunicorn#154]
add auto-reload option for situations when gunicorn is used for development.
using "$ kill -HUP masterpid" for development is not an option.

there is nothing about auto-reload on http://gunicorn.org/run.html so if auto-reload exists please add some docs here.

**Comment by kevinisaac** [comment]
Is there any way to monitor files to reload gunicorn? I am working with falcon framework and using gunicorn's `--reload` option. However,  I need to monitor certain HTML files to reload gunicorn when they are changed.

Adding an option to supply files/directories to be monitored for change would be cool.

**Comment by tilgovi** [comment]
I know asset management frameworks often handle this sort of thing automatically, caching and rebuilding assets based on file changes. Falcon is very minimal by design, and so doesn't handle this. If you can find a good way to expose it usefully to a server hook, the reloader already does have methods for adding additional watched files. Would be happy to review a pull request to that effect.
