### ISSUE TITLE
couverture-io CI runs on recent PRs are stuck pending

### ISSUE THREAD

**Issue by edmorley** [benoitc/gunicorn#1548]
On several recent PRs, the couverture-io CI status is stuck as "Verifying code coverage..." several days after the PR was updated.

**Comment by berkerpeksag** [comment]
Thanks, I noticed that too. @benoitc can we disable it until they resolve the problem?

**Comment by tilgovi** [comment]
I would love to switch to codecov, which I have used to great success in other projects.

**Comment by benoitc** [comment]
@aconrad is there any issue with couverture.io ? btw will it get out of beta ?

@tilgovi what would be the diff?

**Comment by aconrad** [comment]
I need to fix a bug, I should take care of it this weekend and things should be back to normal.

**Comment by tilgovi** [comment]
Couverture is in beta, has little information about what differentiates it, and does not appear to be full-time maintained. I am happy to help test it, but I would be more comfortable using Codecov for our commit status. Is it possible for us to upload reports to Couverture to help out the beta without having it turned on for the repository so that we don't have to rely on it for PRs to pass status checks?

**Comment by benoitc** [comment]
@tilgovi i will let @aconrad answers about the couverture stability and its futire. I thought it would go out of beta faster though ;) 

One sure thing is that we shouldn't block the PRs much. I wouldn't disagree if everyone think we should move. Let's just wait for @aconrad feedback on the issue. Also maybe sending the report is enough for the beta ?  can we link them somewhere ?

**Comment by aconrad** [comment]
I didn't manage to get around it over the weekend. As @benoitc said, it should be a blocker but I'd love to keep couverture.io here if you don't mind/ignore the noise for now. The gunicorn project has been super useful for me so far, but I'm a little behind due to lack of bandwidth, and I apologize for this. Once I get around it this bug, things should be pretty smooth moving forward. Thanks for your understanding.

**Comment by aconrad** [comment]
Ok, I looked into it and it seems that the latest version of coverage.py made a backwards incompatible change that broke many reporting tools out there.

https://bitbucket.org/ned/coveragepy/issues/578/incomplete-file-path-in-xml-report

For now the temporary fix is to pin `coverage>=4.0,<4.4` and have coverage reports be re-generated and sent to couverture.io.

I'll submit a PR for this, but all pending PRs will have to re-run the tests.

**Comment by berkerpeksag** [comment]
@aconrad I've rebased #1569 and reran tests. I think it works fine, can you confirm?

**Comment by aconrad** [comment]
@berkerpeksag yup, that looks much better and we're properly showing you what hasn't been covered by tests! 👍 I think you can close this issue. Just @mention me if you have any other questions! Thanks for your help!
