### ISSUE TITLE
Why restrict access logging?

### ISSUE THREAD

**Issue by tomjaguarpaw** [benoitc/gunicorn#1567]
I want to create a new access logger with

    handler = ...
    logger = logging.getLogger('gunicorn.access')
    logger.addHandler(handler)

But this doesn't work!  The reason it doesn't work is that none of `self.cfg.accesslog`, `self.cfg.logconfig` or `self.cfg.syslog` are set.  I'm very puzzled by [the check for the existence of these attributes in the `Logger` class](https://github.com/benoitc/gunicorn/blob/fc0d9734168ee675723ce09af26b3c8c37fec534/gunicorn/glogging.py#L319).  In fact, this check has existed in some form since [the beginning of this class](https://github.com/benoitc/gunicorn/blame/824801d01768c984d7f6cbd2968cecffc46b0472/gunicorn/glogging.py#L85).

Why restrict access logging to only the cases where one of those attributes is set?  Is there a good reason?  I can't think of one.  I propose deleting that check.

**Comment by tomjaguarpaw** [comment]
Specifically, I propose https://github.com/benoitc/gunicorn/pull/1568

**Comment by tilgovi** [comment]
I think this makes sense to me. The check does seem unnecessary. The only thing I can think that we would want to check is that we still set the access log not to propagate even if no options configure access logging. Otherwise, we will bubble into the `gunicorn` logger, and that seems to be against the intent of the way the access log is used. In other words,` we use the `gunicorn.error` and `gunicorn.access` loggers as purpose-named rather than module-named loggers.

I am not a big fan of a logger with an `access` method, though, and I hesitate to encourage using it as public interface. Can you say more about why you are trying to log to the access log from somewhere else other than Gunicorn internals?

**Comment by tomjaguarpaw** [comment]
> Can you say more about why you are trying to log to the access log from somewhere else other than Gunicorn internals?

What do you mean?  I'm not calling `Logger.access` myself.  I just  want to set up a `logging` logger that logs access to my Gunicorn server.  How else would I do that?

**Comment by tilgovi** [comment]
Gunicorn sets up that logger and does that logging internally. You should be able to use the logging settings to get what you want.

http://docs.gunicorn.org/en/latest/settings.html#logging

**Comment by tomjaguarpaw** [comment]
Yeah but I want more control over logging than that.  I want to be able to log to `sys.stdout`, for example. Indeed I want as much control as the `logging` module provides.  Why would GUnicorn restrict me in that?  I cannot see a reason.

**Comment by tilgovi** [comment]
I suspect that for some users the ergonomics of `--access-logfile` are simpler than configuring Python logging. `--access-logfile -` means log to stdout. Are there other controls you need?

I'm sympathetic, by the way. I still think we might want to remove the checks you point to, I just wanted to know how you ended up with calls to `access()` without using these flags. In my own apps, I use `--logconfig` and customize `gunicorn.access` using an INI file. I think it would be good to support dict config, too, if you would be interested in implementing that.

**Comment by tomjaguarpaw** [comment]
> --access-logfile - means log to stdout. Are there other controls you need?

Sure, I might want to log to stdout *and* to a file, or with a `WatchedFileHandler`, a `RotatingFileHandler`, an `HTTPHandler`, etc., etc..  The `logging` module provides a lot of powerful functionality.  Why would GUnicorn want to stop me having full access to this functionality?

> In my own apps, I use --logconfig and customize gunicorn.access using an INI file

That's all fine, but it's my understanding (correct me if I'm wrong) that the standard way of using the `logging` module is in a manner I outlined in my initial comment:

    handler = ...
    logger = logging.getLogger('gunicorn.access')
    logger.addHandler(handler)

I don't see why this shouldn't be supported by GUnicorn.

**Comment by tilgovi** [comment]
I never said that it shouldn't and I haven't raised any issue with your PR. I just wanted to help in case you had not seen the shorthand options.

I suspect the reason that Gunicorn has the check here is because the common way to use the Gunicorn access log is via the command line flags and it avoids some small amount of overhead to not computer the access log atoms if they aren't going to be used. Perhaps instead of removing the conditional you can change it to `if not self.access_log.isEnabledFor(logging.INFO)`.

**Comment by tomjaguarpaw** [comment]
OK, great.  Thanks for the clarification.  I will amend the PR.

**Comment by benoitc** [comment]
I commented the PR about the reasoning behind that check. However it's about time to make the logging system more configurable , i opened #1572 to discuss it. 

In the mean time the changed proposed by @tilgovi would solve the current issue. Any PR that does it would be accepted :)

**Comment by tilgovi** [comment]
Closing in favor of the discussion in #1568.
