### ISSUE TITLE
Gunicorn for chat bot

### ISSUE THREAD

**Issue by LoveUrfuNo** [benoitc/gunicorn#1594]
Hello! I have a chat bot written in python django and deployed with gunicorn. I started 12 workers on cpu with 2 cores. More than 12 I do not run, because the documentation is not recommended, but my cpu is loaded 7 percent maximum. Why I can not run 20 processes and more? Maybe I need run worker with multiple threads? I tried, but bot send many responce on one request. How can I start using all the resource of the processor? Maybe it's worth deploying the application to a different technology instead of gunicorn? Gunicorn i'm running so: nohup gunicorn --workers=12 --max-requests=5000 --bind 127.0.0.1:8000 mybot.wsgi:application & . Thank you.

**Comment by tilgovi** [comment]
As I said in the other issue (https://github.com/benoitc/gunicorn/issues/1045) this is not enough information to help you.

You can run as many processes as you like. Where does the documentation say to use no more than 12? If you run many more processes than you have cores on your system it's not usually the best way to scale because it adds a lot of scheduling overhead for the OS. That is what the asynchronous workers are good for.

You need to test your own application and do your own benchmarking.

It would have been nice if you provided more information and demonstrated that you are interested in diagnosing your performance issues. Instead, you copy and pasted your same question on a new issue and down voted my comment. Please, be more respectful if you are asking for assistance.

**Comment by tilgovi** [comment]
I'm sorry if I was harsh here, been feeling bad about it.

Please take some time to benchmark your application, read about the different workers, figure out whether the bottleneck is network or not. If Gunicorn is using only 7% of your CPU then you are probably not sending it enough requests or your network settings on the machine need to be tuned to deal with more requests. More details about latency might help, but if your requests are completing quickly and Gunicorn is using only 7% CPU then you might need a deeper connection backlog or might have to look into whether other software or network is limiting the performance.

**Comment by LoveUrfuNo** [comment]
I cant give more information because i dont now what you need... I just want to learn different ways of working with asynchrony and use my CPU full. I can give my metrics. Maybe i need use different worker class? For example gevent and set worker_connections.  Or maybe i need use some worker class, 
that allow me use multithread with many workers? Or maybe i can just set workeers=n, where n is 50 or more if my CPU is use 7 percent? Thank you.
![image](https://user-images.githubusercontent.com/25740734/30519769-cdb20b1a-9be9-11e7-870d-740d0bae8f64.png)

**Comment by tilgovi** [comment]
Thanks. Here are some questions to ask:

1. Are you generating as much load as the server can handle? Maybe Gunicorn is just handling all the traffic easily.

2. Are requests taking a long time? Where do they spend the most time: connecting, requesting, waiting for a response? Tools like ab (Apache bench) can give you this information.

For most workloads, you don't want more than one or two workers per core. The reason is that the operating system starts spending more and more time scheduling and workers get interrupted in the middle of requests more often, causing more latency. This is where the genent, eventlet, tornado, and asyncio workers help because they cooperatively schedule work on multiple connections without the overhead of process scheduling.

First thing to check is that you're actually generating load, though.

**Comment by LoveUrfuNo** [comment]
In logs on vk.com (social network where my bot is) I often look: "Error: Timeout was reached". 
    I started gunicorn and used Apache bench:

"**workers=8 --max-requests=5000**"

- ab -n 1000 -c 50
![image](https://user-images.githubusercontent.com/25740734/30524287-86e70df4-9c3c-11e7-9ec3-e36f50029db7.png)

- ab -n 5000 -c 150
![image](https://user-images.githubusercontent.com/25740734/30524304-e7ff9b4c-9c3c-11e7-8536-8d09f30902ed.png)

- ab -n 10000 -c 300
![image](https://user-images.githubusercontent.com/25740734/30524352-ee20ca40-9c3d-11e7-8ed8-89c0197ae1e4.png)

- ab -n 10000 -c 500
![image](https://user-images.githubusercontent.com/25740734/30524371-25971222-9c3e-11e7-8cae-c56d9f26b8f1.png)

POST
- ab -n 100 -c 20 -T ‘application/json’ -p postfile.json
![image](https://user-images.githubusercontent.com/25740734/30524382-5090fe84-9c3e-11e7-98f6-999694763f8c.png)

-  ab -n 2000 -c 100 -T ‘application/json’ -p postfile.json
![image](https://user-images.githubusercontent.com/25740734/30524430-3c01a454-9c3f-11e7-9feb-f218f5740078.png)

![image](https://user-images.githubusercontent.com/25740734/30524459-df8b46f2-9c3f-11e7-8cad-4ac6165ad008.png)

When I testing post (ab -n 100 -c 10 -T ‘application/json’ -p postfile.json), then in logs wrote many "Too many requests! Sleeping 0.5 sec...
", even I set --max-requests=10000. Same if i set max requests 0. 

"**-k gevent --workers=5**"

- ab -n 100 -c 10 -T ‘application/json’ -p postfile.json
![image](https://user-images.githubusercontent.com/25740734/30524656-a8f8aec8-9c43-11e7-9077-62c4a8ad299a.png)

- ab -n 1000 -c 50 -T ‘application/json’ -p postfile.json
![image](https://user-images.githubusercontent.com/25740734/30524660-c2eadf36-9c43-11e7-88e9-c76531fa57a0.png)

"**-k gevent --workers=5 --threads=5**"

- ab -n 100 -c 10 -T ‘application/json’ -p postfile.json
![image](https://user-images.githubusercontent.com/25740734/30524777-99d13ada-9c45-11e7-9c59-912f106169a6.png)

- ab -n 1000 -c 50 -T ‘application/json’ -p postfile.json
![image](https://user-images.githubusercontent.com/25740734/30524785-c395cc3c-9c45-11e7-8827-0bceb16c3d9c.png)

"**-k gthread--workers=5 --threads=5**"

- ab -n 100 -c 10 -T ‘application/json’ -p postfile.json
![image](https://user-images.githubusercontent.com/25740734/30524823-a1e99f2c-9c46-11e7-8d8f-086999affe22.png)

- ab -n 1000 -c 50 -T ‘application/json’ -p postfile.json
![image](https://user-images.githubusercontent.com/25740734/30524836-c3d427ba-9c46-11e7-8750-f5753962cb9c.png)

- ab -n 300 -c 100 -T ‘application/json’
![image](https://user-images.githubusercontent.com/25740734/30524856-1f0f1aae-9c47-11e7-8582-07ae981dd717.png)

More fast is gthread for me i think, but in logs I still see "Too many requests! Sleeping 0.5 sec...", but not more than with sync. If I run -c 50 and more, then a lot "Too many requests! Sleeping 0.5 sec..." in logs, and Time per request more depending on -c. 

How do I configure it before an active user flow? When the bot will respond simultaneously 1000 and more people. And what I'm setting is wrong, then I have many "Too many requests! Sleeping 0.5 sec..."? I know that it for memory leak protection, bit I think my app needn't it so often. And I am right about my choice on gthread?

**Comment by LoveUrfuNo** [comment]
And metrics during testing
![image](https://user-images.githubusercontent.com/25740734/30525027-61f1cad0-9c4a-11e7-8e97-e2b3c798ccfc.png)

**Comment by tilgovi** [comment]
I don't know where "Too many requests. Sleeping..." comes from. That is not a Gunicorn message as far as I know. That sounds like an error from your load balancer or an external service. It sounds like a rate limit, like some outbound HTTP request you made got a 429 response. It could be a response from vk, or something else. Maybe you're saving the posted data to S3 or some other service?

Since you are spending very little CPU time in sys, it seems like you get very little scheduling overhead. You *could* try more workers.

Using `--threads` forces the worker to `gthread`. See the note in http://docs.gunicorn.org/en/latest/settings.html#threads about this. So `--threads` implies `-k gthread`. In your test where you set `-k gevent --threads 5` it is the same as `-k gthread --threads 5`.

It seems like the sync worker is best for you, or maybe gthread. You could try a small number of threads and a high number of workers. Something like `-k gthread --workers 10 --threads 2`, maybe. This is just a guess.

Good luck.

**Comment by tilgovi** [comment]
You might also try increasing the `--backlog` setting if you find that requests get dropped.

**Comment by LoveUrfuNo** [comment]
Okey, I will try what you advise. Do you now about it: <<How do I configure it before an active user flow? When the bot will respond simultaneously 1000 and more people, I get "pr_socket_recv: Connection reset by peer (104)" for example with "- ab -n 10000 -c 500">>? It is not Gunicorn problem? If not then what is problem you think? Maybe it is vk again?
**And my main question :D**
**vk.com** block more then 3 requests per second, and return "Too many requests. Sleeping...", you was right about it. Vk API developer told me, then he dont know about how vk checked who send requests. He give me advise: use not one token for authorization. 
How to use different token for each worker? And what do you think about it? Is many tokens for auth help me?

**Comment by tilgovi** [comment]
> How to use different token for each worker? And what do you think about it? Is many tokens for auth help me?

You will have to figure out how to architect your application for this. I do not know what VK rules are, how you get more tokens, or what tokens correspond to. It sounds like you want more than a token per worker, because workers might make many requests in a second. This is the concern of your application now, and not Gunicorn.

If you have more questions about Gunicorn threads vs processes and worker types, please feel free to open an issue with a question. Support for other questions is beyond the scope of this issue tracker.
