### ISSUE TITLE
After using gevent work class, using SSH can't connect to mysql

### ISSUE THREAD

**Issue by breakstones** [benoitc/gunicorn#1624]
_mysql_exceptions.OperationalError: (2013, "Lost connection to MySQL server at 'waiting for initial communication packet', system error: 110")

```py
import MySQLdb
from sshtunnel import SSHTunnelForwarder

with SSHTunnelForwarder(
        (ssh_host, ssh_port),
        ssh_username='user',
        ssh_password='pwd',
        remote_bind_address=('db_host', 3306),
        local_bind_address=('0.0.0.0', 5678)) as tunnel:
        conn = MySQLdb.Connect(db='database',
                               host='127.0.0.1',
                               port=5678,
                               user='db_user',
                               passwd='db_pwd',
                               charset='utf8',
                               connect_timeout=4)
```

using sync work class,everything is all right

**Comment by tilgovi** [comment]
I think the problem is that `MySQLdb` uses a C driver for communication that is probably causing incompatibility with gevent sockets.

Try using a pure python version like `pymysql` or spending some time debugging with `gevent` outside Gunicorn. It is unlikely that this is a problem with Gunicorn itself.

**Comment by breakstones** [comment]
Thank you very much !!! @tilgovi

**Comment by breakstones** [comment]
Thank you very much @tilgovi
