### ISSUE TITLE
How to configure Server Hooks while using pastedeploy configuration?

### ISSUE THREAD

**Issue by winglq** [benoitc/gunicorn#1631]
I need to use a customer worker_int hook, but I don't know how to write the paste.ini. Is this supported?

**Comment by tilgovi** [comment]
You could set a gunicorn config file in your paste configuration and then define it in the gunicorn config. The default is `gunicorn.conf.py` if you don't specify, so just creating that file in the directory where you run your app works, too.

**Comment by winglq** [comment]
@tilgovi 
my paste configure is as following, and it does not work. But if I copy /path/to/config.py to pwd and named to gunicorn.conf.py, the hook was  called.  How could I set a gunicorn config file in paste configuration? Thanks.
`
...
[server:main]
use = egg:gunicorn#main
...
config = /path/to/config.py
`

**Comment by fenghui2013** [comment]
the same question.

**Comment by benoitc** [comment]
The supported way to use paste with gunicorn is the following instead of using the paste server:
http://docs.gunicorn.org/en/stable/run.html#paste

You can pass the --config variable on this command line. The other way is to pass the following to your paste:ini:

```
[server:main]
config=
```

It should work: https://github.com/benoitc/gunicorn/blob/master/gunicorn/app/pasterapp.py#L161 but this method is currently deprecated.

**Comment by benoitc** [comment]
answered and no feedback since awhile.
