### ISSUE TITLE
gunicorn  process number not match workers number?

### ISSUE THREAD

**Issue by eromoe** [benoitc/gunicorn#1633]
I have two projects which use supervisor to monitor.

supervisor conf  command like:
```
command=gunicorn -w 5 -b 0.0.0.0:12000 'run:build_app(action="prod")'

command=gunicorn -w 6 -b 0.0.0.0:16000 run:app --reload --timeout 60 --log-level DEBUG
```

one set 5 workers(`-w 5`),  another set  6.  But I found  number does not match

```
[root@s01 ~]# ps -aux|grep 0.0.0.0:16000| grep -v grep |wc -l
7     # should be 6
[root@s01 ~]# ps -aux|grep 0.0.0.0:12000| grep -v grep |wc -l
26   # should be 5
[root@s01 ~]# ps -aux|grep gunicorn| grep -v grep |wc -l
33 
```

**Comment by tilgovi** [comment]
The `7` is expected because that is `6 + 1`: `6` workers and `1` arbiter that manages them.

The `26` is unexpected and probably because you have extra Gunicorn instances started by accident.  In the past, this would have been an error and some would have died because they could not bind the port. I suspect the reason that you can start many right now is due to SO_REUSEPORT, which we plan to make optional, opt-in, again. See #1603.

If you kill all your Gunicorn processes and start each service, please confirm that you see `6` and `7` processes, respectively, after starting Gunicorn. If that is the case then I don't think there is any new bug here.

Another possibility is that your own application calls `fork()`.

Let us know what you find. Thanks!

**Comment by eromoe** [comment]
Thanks for you tips,  I found that there is a function `jieba.enable_parallel(4)` .   So, 5 workers, each worker  start 4 other,  total (1+4) *5 +1 = 26 .
