### ISSUE TITLE
gunicorn with eventlet runs threads in sequential manner

### ISSUE THREAD

**Issue by ykg2910** [benoitc/gunicorn#1830]
Sample Code -

```
from flask import Flask
app = Flask(__name__)

import threading


class SThread(threading.Thread):

    def __init__(self):

        threading.Thread.__init__(self)


    def run(self):
        # place holder for blocking IO task
        for i in range(1, 1000):
            print 0


t = SThread()
t.start()

# place holder for blocking IO task
for i in range(1, 1000):
    print 1

t.join()

@app.route('/')
def hello_world():
    return 'Hello, World!'
```

====================================

When you start your server like this, gunicorn run:app -b 0.0.0.0:8000, you will see all 0 and 1 will be in random order, main thread and child thread are running parallel. But when you run same piece of code with 'gunicorn --worker-class run:app -b 0.0.0.0:8000', you will see first there will be all 0s and then there will be all 1s. That means main thread and child thread are not running parallel. Is this expected behaviour? And how can I use eventlet and make use of threading behaviour?

**Comment by tilgovi** [comment]
Eventlet and other event-driven I/O frameworks cooperatively schedule around blocking I/O calls. When these frameworks patch the built-in threading library, they turn threads into these cooperative co-routines. This is the expected behavior. These are not parallel frameworks, but they allow for _concurrency_ around I/O. You will see that concurrency if you make a call to an I/O API that blocks, such as `socket.read()`. Other tasks run while I/O is waiting.

**Comment by ykg2910** [comment]
Thanks a lot for quick response. I have added 't.join' statement, that I forgot earlier. I want to join these 2 execution streams at that point. How can I achieve this kind of threading behaviour with eventlet. Can you put me in some direction? Or can you provide a coed snippet which changes this thread based code into eventlet based code, and I get same random behaviour.

**Comment by tilgovi** [comment]
Eventlet is a coroutine library. It is not for threading. Is there a reason you're trying to use eventlet?

**Comment by ykg2910** [comment]
I am using it for flask_socketio. With threading async_mode, I am not getting events reliably.

**Comment by tilgovi** [comment]
Can you share a minimal example that reproduces your issue?

**Comment by ykg2910** [comment]
Are you asking for flask_socketio example?

**Comment by tilgovi** [comment]
I am asking for an example that shows how a real application experiences issues with Gunicorn and eventlet. Otherwise, I don't understand the error you have because the code you have shared so far works the way eventlet is designed to work.

**Comment by ykg2910** [comment]
How can I use eventlet with OS based threads? Is this possible to use OS based threads with eventlet green threads?

**Comment by tilgovi** [comment]
Check out the documentation here: http://eventlet.net/doc/threading.html#tpool-simple-thread-pool

You may also be able to get the original `threading` module somehow, if eventlet keeps a reference to it. It looks like the `eventlet.patcher.original()` function might be able to give you the un-patched `threading`: https://github.com/eventlet/eventlet/blob/master/eventlet/patcher.py#L168

**Comment by ykg2910** [comment]
Thanks. For first suggestion, thing is coroutine can start thread but while the calling coroutine blocks on its completion, so eventlet coroutine and thread will not be running simultaneously on a multiprocessor system. 

Towards other suggestion, I can not make something out of it yet, I guess I have to look little deep into it.

Can you suggest a way in which 2 execution streams an run in parallel in multiprocessor system?

The problem is I have 2 big files which I have to read, and they are independent file, so if I design a simple threading based solution, main thread will start a child thread which will read from file 2 and main thread will read from file 1 and then will wait for child thread using join() method. Can I achieve this kind of behaviour with eventlet.

Please look at example, I would like to achieve something like that.
```

import threading

class SThread(threading.Thread):

    def __init__(self):
        threading.Thread.__init__(self)

    def run(self):
         #read from file 2
         pass

t = SThread()
t.start()

# read from file 1

t.join()
```

**Comment by ykg2910** [comment]
So does it mean I can not achieve this behaviour If I use gunicorn with workerclass eventlet and gevent?

**Comment by tilgovi** [comment]
From what I read, gevent does provide some wrappers to implement file I/O with a threadpool. See here: http://www.gevent.org/api/gevent.fileobject.html

In general, file I/O (unlike socket I/O) is not async in many frameworks and platforms without a thread pool. For eventlet, you would need to use the tpool module to read in parallel from files.

Please see if the article posted in response to #1836 helps.

**Comment by tilgovi** [comment]
From the `tpool` documentation:

> The function will be run in a random thread in the pool, while the calling coroutine blocks on its completion

Calling `t1.wait()` and `t2.wait()` does not make it sequential. What _is_ sequential is the spawning of `t1` and `t2` and their execution until they defer to the thread pool.

``` python
>>> import time
>>> import eventlet
>>> from eventlet import tpool
>>>
>>> def sleep():
...     print('sleeping')
...     time.sleep(5)
...     print('slept')
...
>>>
>>> t1 = eventlet.spawn(tpool.execute, sleep)
>>> t2 = eventlet.spawn(tpool.execute, sleep)
>>> t1.wait()
sleeping
sleeping
slept
slept
>>> t2.wait()
>>>
```

Both threads in the thread pool are running at the same time, which is why `sleeping` is printed twice before `sleep` is printed.

Notice that since eventlet green threads are scheduled _cooperatively_, neither t1 nor t2 starts until the main thread calls `t1.wait()`. At that point, `t1` dispatches to the `tpool` and then yields until the execution of `sleep()` finishes. The `t2` green thread can then run and do the same thing.

The difference between green threads and "regular" threads is that green threads are scheduled cooperatively and "regular" threads are scheduled preemptively. In order for another green thread to run the currently running green thread must yield. In eventlet and gevent, yielding happens implicitly whenever _blocking_ network I/O calls are made, such as `socket.read()`.

I hope that helps clarify.

**Comment by tilgovi** [comment]
@ykg2910 is there more information that I can help you with?

**Comment by ykg2910** [comment]
@tigovi I am sorry to miss it. It was a great help. Thanks.

**Comment by shreeramk** [comment]
@ykg2910 I have exactly the same requirement as you had. Were you able to run threads un-sequentially?
