### ISSUE TITLE
Docs wesite invalid certificate

### ISSUE THREAD

**Issue by muhlemmer** [benoitc/gunicorn#1862]
When visiting https://docs.gunicorn.org Firefox gives the following error:

docs.gunicorn.org uses an invalid security certificate. The certificate is only valid for the following names: *.readthedocs.org, readthedocs.org Error code: SSL_ERROR_BAD_CERT_DOMAIN

**Comment by tilgovi** [comment]
Thanks, @muhlemmer!

cc @benoitc 

To have HTTPS work for readthedocs, we have to have the CNAME point to `gunicorn-docs.readthedocs.io` rather than `gunicorn-docs.readthedocs.org`, it seems.

https://docs.readthedocs.io/en/latest/alternate_domains.html#cname-ssl

We could also have gunicorn.org on HTTPS if we use the newer GitHub Pages HTTPS setup.

https://help.github.com/articles/setting-up-an-apex-domain/

**Comment by benoitc** [comment]
change have done, some dns may not have been received yet the changes. closing the issue anyway. Thanks @muhlemmer & @tilgovi for the notice
