### ISSUE TITLE
worker_tmp_dir setting should use /dev/shm tmpfs by default

### ISSUE THREAD

**Issue by ciarancourtney** [benoitc/gunicorn#1863]
That or http://docs.gunicorn.org/en/stable/faq.html#blocking-os-fchmod should just recommend setting `worker_tmp_dir=/dev/shm`

Perhaps there should be a Cloud/AWS section in docs collecting all of these perf caveats?

**Comment by benoitc** [comment]
+1 to add it to the doc, also we should mention on which OS it can be used.

However keep it posix by default even if it's not very trendy these days.

**Comment by benoitc** [comment]
@ciarancourtney don't hesitate to send us a PR for it btw :)

**Comment by tianchu** [comment]
Hi @benoitc @ciarancourtney,

I recently noticed that lots of our gunicorn processes sporadically blocks on the uninterruptible sleep (D) state. After a few mins, they recover from that state by themselves. See vmstat result below.

```
procs -----------memory---------- ---swap-- -----io---- --system-- -----cpu-----
 r  b   swpd   free   buff  cache   si   so    bi    bo   in   cs us sy id wa st
 0 53      0 136512  38016 239784    0    0  2371    68  216  200  4  1 91  4  0
 3 49      0 126088  39260 242172    0    0  3676    20 3303 4944 32  7  0 60  1
 0 59      0 156316  39144 226552    0    0  6044   216 2766 3801 23  8  0 70  0
 0 53      0 137712  39844 231748    0    0  5872     4 2304 3055 14  4  0 83  0
 0 47      0 128720  41784 236492    0    0  6776    32 2430 3313  7  2  0 91  1
 0 60      0 147836  35584 210744    0    0  7112     4 2180 3021 21  7  0 72  0
19 32      0 136016  36812 218032    0    0  8520    16 2757 3416 10  4  0 86  0
 1 52      0 134056  37864 222840    0    0  5836   112 2860 3717 15  3  0 81  0
 0 36      0 121856  39820 227528    0    0  6608    48 2844 3865  8  6  0 87  0
 0 60      0 142896  36100 206428    0    0  6232    20 3395 4236  9  8  0 82  0
```

We are running gunicorn within docker containers on AWS. OS is Debian, and we are using the default worker_tmp_dir  `/tmp` instead of `/dev/shm`. So I suspect that's what sporadically causing gunicorn processes stuck in the `D` state. 

Based on the doc, we are changing it to `/dev/shm` anyway, but I think it would be helpful if any of you can help confirm my guess. It might be helpful for others who stumble on this thread in the future as well.

Thanks!
