### ISSUE TITLE
Website blocked mixed content

### ISSUE THREAD

**Issue by cropr** [benoitc/gunicorn#1870]
Opening the website gunicorn.org gets the following error in the console.
_Blocked loading mixed active content “http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js”_
Swicthing to any section fails.
Culprit is the  `<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.2/jquery.min.js"></script>`
which should be https

**Comment by berkerpeksag** [comment]
Thanks for the report! This has already been fixed in https://github.com/benoitc/gunicorn/commit/ab7541f7671037f45bdbbad574371c8eaf4f0ec5. I've just cherry-picked it into the `gh-pages` branch in https://github.com/benoitc/gunicorn/commit/2de27fa7b5e023de31122608602f41350cbe32b3.

gunicorn.org should load properly now. Closing this as 'fixed'.

**Comment by benoitc** [comment]
@berkerpeksag btw the tools ghp-import take care of it, there is no need to cherry-pick =)
