### ISSUE TITLE
Worker timeout, critical error message?

### ISSUE THREAD

**Issue by gforcada** [benoitc/gunicorn#1881]
Hi,

we have sentry plugged into gunicorn to server our Django app and every now and then (200 events on our staging environment) we get this report about `WORKER TIMEOUT` critical message.

It doesn't feel that *critical* to me given that on your docs http://docs.gunicorn.org/en/latest/settings.html#timeout it is stated that the worker just gets restarted...

What's so critical about restarting a worker that was just plain idle? Maybe I'm missing that, otherwise, would it be possible to lower its severity to something like `info` or `warning`? :thinking: 

Thanks!

**Comment by tilgovi** [comment]
This doesn't happen when a worker is idle, it happens when a worker is busy. This can mean your worker is stuck / blocked / failed and sometimes this is critical. If you have a reverse proxy in front of Gunicorn handling request timeouts or something then it's not critical, but otherwise this would be a quiet failure of your application to complete requests and that can definitely be a serious problem.

**Comment by tilgovi** [comment]
Perhaps warning is better, maybe, but I'd be hesitant to say we should change it, since that could cause existing deployments to stop reporting errors they otherwise care about.

**Comment by gforcada** [comment]
@tilgovi thanks for pointing out that is when a worker is busy, I didn't get that by reading the docs I pointed above. There should be no need to change the severity then.

**Comment by tilgovi** [comment]
Thanks for following up! If there's any change you'd like to see to the documentation, please submit a PR and I'd be happy to review it!
