### ISSUE TITLE
TLSv1.3 support

### ISSUE THREAD

**Issue by benoitmaudet** [benoitc/gunicorn#1933]
Hello,

When do you plan to implement TLSv1.3 ?

Regards,

**Comment by javabrett** [comment]
I suspect #1680 or similar will be needed for this, but noting that Python 3.7 does not have an `ssl.PROTOCOL_TLSv1_3` constant, and all the preceding `ssl.PROTOCOL_TLSv1_2` etc. are now deprecated, replaced by `ssl.PROTOCOL_TLS` and .  Otherwise #1114 / #1890 / c66957bbe9ead62e625156e632595cd7886b341d would have helped (unreleased, on `master` at time of writing).

It looks increasingly like these need to be negotiated via the context with https://docs.python.org/3/library/ssl.html#ssl.SSLContext.minimum_version and https://docs.python.org/3/library/ssl.html#ssl.SSLContext.maximum_version using constants defined in https://docs.python.org/3/library/ssl.html#ssl.TLSVersion e.g. [ssl.TLSVersion.TLSv1_3](https://docs.python.org/3/library/ssl.html#ssl.TLSVersion.TLSv1_3)

I have some unfinished code that will probably help.  If there are folks ready to contribute to it I can push it sooner rather than later.

**Comment by benoitc** [comment]
@javabrett i'm confused. What needs to be done right now? Any patch that brings the support of TLS 1.3 is OK. Should be easier with the new master since we only handle python 3.

**Comment by javabrett** [comment]
Actually all of `ssl.OP_NO_TLSv1`, `ssl.OP_NO_TLSv1_1` and `ssl.OP_NO_TLSv1_2` are themselves deprecated in Python 3.7+, since OpenSSL deprecated the equivalent `-no_ssl3` `-no_tls1` `-no_tls1_1` `-no_tls1_2` `-no_tls1_3` in favour of `-min_protocol`, `-max_protocol` in OpenSSL 1.1.0, which Python now has as `SSLContext.minimum_version`, `SSLContext.maximum_version` with enums from `ssl.TLSVersion`.  That's all Python 3.7+ though, but further points to consistent use of `SSLContext` being the end-goal.

**Comment by javabrett** [comment]
Another thing worth pointing out is that testing for this requires a very specific environment, since OpenSSL 1.1.1+ is required for TLS 1.3 support.  If for example you run the standard Python 3.7.2 for MacOS you will get (from some verbose test config I have):

> OpenSSL 1.1.0j  20 Nov 2018 WITHOUT support for TLS 1.3, using TLS 1.2

... noting that on MacOS at least, Python ships its own private OpenSSL, but still not quite new enough.

Also - we could do with some public regression/sysint tests for this kind of thing ... I'm finding myself running the examples manually to test at the moment - are there automated integration tests suites?

**Comment by benoitc** [comment]
it will depends on the installed version of ssl. By default gunicorn is using the highest protocol available on the machine.
