### ISSUE TITLE
make sure all examples work on python 3

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#1961]
some <del>tests</del><ins>examples</ins> are not working on python 3. make sure they are.

**Comment by javabrett** [comment]
We could list or link any failing tests here.

**Comment by tilgovi** [comment]
- [ ] log_app.py returns string instead of bytes
- [ ] echo.py tries to return an invalid, non-ascii header
- [ ] readline.py has the same invalid header, but commented out
  - [ ] readline.py is also a bad name, because it confuses the Python REPL on my machine when running Python interactively from the examples directory
- [ ] test.py has the same invalid header, but commented out
