### ISSUE TITLE
gunicorn start

### ISSUE THREAD

**Issue by policeme** [benoitc/gunicorn#1963]
how gunicorn start workers with serial, not parallel
@benoitc

**Comment by tilgovi** [comment]
Thanks for opening an issue. Can you explain your question with more detail? I don't understand it.

And please don't @ maintainers on issues. We do our best to be responsive. Unless you need a response from one particular person, it's best to let the community answer your questions without nagging any one individual.

**Comment by policeme** [comment]
sorry, I don't know it.
 my problem is down.
1.I want start 10 workers with gunicorn. every worker have tensorflow model, before tensorflow model start, I have to set gpu number, where tensorflow model stay.
2. I get gpu information from nvidia-smi output message. 10 workers get message in the same time, I want worker get message when last worker down, this is I called serial, but gunicorn is parallel.

can gunicorn start worker serial?

**Comment by tilgovi** [comment]
You probably want to call `nvidia-smi` _before_ you start Gunicorn. See if the [Custom Application](http://docs.gunicorn.org/en/latest/custom.html) documentation helps your case.

**Comment by policeme** [comment]
sorry, I want call nvidia-smi, when last-worker finish initialize

**Comment by tilgovi** [comment]
Can you explain your use case in even more detail? Is it important that you call it only once? Can you call it from every worker?

In general, coordinating between workers is not something Gunicorn provides. Each worker is independent.

You might be able to use server hooks and Arbiter internals to know when the workers are all initialized: http://docs.gunicorn.org/en/latest/settings.html#server-hooks

You also might want to preload your app so that it initializes only once: http://docs.gunicorn.org/en/latest/settings.html#preload-app

**Comment by benoitc** [comment]
@policeme bump

**Comment by benoitc** [comment]
to add to that worker are started one by one but there is no guarantee on the time they are available. As said @tilgovi you can use one of the hooks to do that for now.

**Comment by benoitc** [comment]
closing the discussion as there have been no update since a while. feel free to start a new one with more details if needed.
