### ISSUE TITLE
[Discuss] Streaming large responses with the synchronous worker

### ISSUE THREAD

**Issue by tilgovi** [benoitc/gunicorn#1974]
This issue is related to other conversations about what the `timeout` means—or should mean—for different work types.

The synchronous worker is great for its simplicity, but sometimes it may be useful to send longer responses without the worker being killed. See #1968, for example.

Rather than expose any internals of Gunicorn, maybe Gunicorn can call `notify()` while streaming a response iterator.

There are complications with `sendfile()`. I haven't otherwise thought hard about the issue. I want to start the conversation, though.

**Comment by benoitc** [comment]
I'm not convinced the sync worker should take care of it. taking a worker busy for a long time would reduce the number of accepted requests. Where the sync worker is designed for fast and stateless requests which is most of the time expected from a web server. Outside the technical simplicity of it I quite like the simplicity of it at a user level since all the expectations are set (even if we may want to improve the doc).

Maybe it's time to introduce a new race of pure python worker that can replace along the time the sync worker as the default. We have a good start with the threaded worker using its own eventloop. Maybe we can provide a new worker that can switch transparently the context during long requests (like when streaming) using async and an eventloop?

**Comment by tilgovi** [comment]
That's good feedback. Maybe the first thing is to clarify documentation (as we have in other issues) around what the expectations for worker timeout are and how to set a request timeout for any worker type (if we want that feature).

**Comment by tilgovi** [comment]
For example, if we had a `--request-timeout` and a `--worker-timeout`, the sync worker could support iteration with `notify()` between chunks so that `--worker-timeout` can be shorter than `--request-timeout`, but still not be forever.

**Comment by benoitc** [comment]
> For example, if we had a --request-timeout and a --worker-timeout, the sync worker could support iteration with notify() between chunks so that --worker-timeout can be shorter than --request-timeout, but still not be forever.

Hrm not sure I like it. I would prefer the simple rule  to kill it when a request is too long. For the documentation which part do you think we need to edit?

**Comment by tilgovi** [comment]
The current situation is very confusing because the `--timeout` option effectively functions as a request timeout for the sync worker, but not for any other worker type.

I see some options:

1. Try to improve the documentation so that the meaning of `--timeout` is clear to users.
2. Implement a request timeout that works the same for all workers.

The second option might mean that we have a separate `--worker-timeout` and `--request-timeout`, so that each one behaves consistently for all workers.

Currently, I believe that `--timeout` is _both_ a worker heartbeat timeout and a request timeout for the sync worker, but it is _only_ a worker heartbeat timout for the others.
