### ISSUE TITLE
app_iter continues to completion after client disconnection

### ISSUE THREAD

**Issue by qlands** [benoitc/gunicorn#2010]
I'm reporting this bug as a result of [https://stackoverflow.com/questions/55209482/server-sent-events-with-pyramid-how-to-detect-if-the-connection-to-the-client](https://stackoverflow.com/questions/55209482/server-sent-events-with-pyramid-how-to-detect-if-the-connection-to-the-client)

app_iter would disconnect under normal circumstances, for example where the use browse somewhere else. However, app_iter does not receive a close in **abnormal circumstances**, for example when the computer is powered off.

This heavily affects SSE vents since app_iter could be looked in an endless loop.

**Comment by tilgovi** [comment]
Do you see this with every worker type, or is there a specific worker type you are using?

**Comment by qlands** [comment]
I use gevent

**Comment by jamadden** [comment]
There's a possibly related issue over at https://github.com/gevent/gevent/issues/1382

The referenced changes to the waitress server had to do with buffering, AIUI. gevent's pywsgi server (WSGIHandler) doesn't do any buffering, though: when the returned iter yields data, [it gets written to the socket](https://github.com/gevent/gevent/blob/master/src/gevent/pywsgi.py#L895). [At that point](https://github.com/gevent/gevent/blob/master/src/gevent/pywsgi.py#L702) we should notice the socket's been closed via an exception (once the OS's TCP stack detects it --- which can take some minutes) and immediately [close the generator](https://github.com/gevent/gevent/blob/master/src/gevent/pywsgi.py#L913).

I *think* you have to opt-in to the gevent WSGIHandler with the `GeventPyWSGIWorker` class (`gevent_wsgi` or `gevent_pywsgi` instead of just `gevent`). If you wish you could try testing that instead of gunicorn's default handler. (Without looking I'm not sure how gunicorn handles app iters.)

**Comment by benoitc** [comment]
i'm not sure how it can happen even with the gevent worker there. When the socket hangs it will also [stop the iteration.](https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/base_async.py#L125).  Same for other workers. Closing the issue then. feel free to reopen it if needed.
