### ISSUE TITLE
log containing Chinese are displayed nonnormally

### ISSUE THREAD

**Issue by luckrill** [benoitc/gunicorn#2107]
My application
Flask runs.  Logs containing Chinese are displayed normally.

Publish and run with gunicorn, log output at / var / log / gunicorn. log
Chinese Partial  not displayed properly

**Comment by benoitc** [comment]
can you provide a simple example? It would be helpful as none of current maintainers (to my knowledge) are speaking one of the Chinese dialect. which unicode spec is needed?

**Comment by benoitc** [comment]
@luckrill bump

**Comment by luckrill** [comment]
![WX20191123-141602](https://user-images.githubusercontent.com/5372899/69474463-6c699580-0dfc-11ea-8312-78f366465b1a.png)
this is log image, don't know why.

**Comment by tilgovi** [comment]
The characters are URL-encoded because they are part of the request line, logged with the `%r` atom of the access log format.

What does the flask dev server you are using display?

I'm not sure we should do anything here, but I can definitely see why this is less friendly than showing the URL-encoded characters.

**Comment by tilgovi** [comment]
Example from a small snippet of the log (request path truncated for brevity):

```
>>> urllib.parse.unquote('GET /?who&key=%E6%BF%80 HTTP/1.1')
'GET /?who&key=激 HTTP/1.1'
```

**Comment by luckrill** [comment]
thanks, thanks 
can close this issue
