### ISSUE TITLE
release. 19.10 or 20.0?

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#2112]
i am wondering which version number to give to the next version. I think due to our timing it may be better to bump directly to 20.0 to notify about a major release instead of 19.10. What do you think? Any feedback is welcome.

**Comment by sirkonst** [comment]
I agree, version 19.0 was released at 2014-06-12 :-)

**Comment by jamadden** [comment]
The `news.rst` file is woefully out of date so it's hard to be sure exactly what's changed without in-depth analysis, but if we're talking about releasing from `master`,  then the next version really needs to be a major version bump, 20.x. There are very incompatible changes in 20.x compared to 19.x, notably dropping support for Python 2.

I would strongly recommend that we add an appropriate `python_requires=` line to setup.py so that pip knows not to try to install gunicorn 20 on Python 2. Otherwise users and maintainers alike are in for a bumpy ride.

**Comment by benoitc** [comment]
>I would strongly recommend that we add an appropriate python_requires= line to setup.py so that pip knows not to try to install gunicorn 20 on Python 2. Otherwise users and maintainers alike are in for a bumpy ride.

@jamadden can you send a PR for that?

**Comment by jamadden** [comment]
Whoops, [it's already there](https://github.com/benoitc/gunicorn/blob/master/setup.py#L97): 
```python
    python_requires='>=3.4',
```

I just missed it on the first scan. I'm used to more complicated strings like `python_requires=">=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*,!=3.4.*"`.

**Comment by di** [comment]
Why not both? #2022 has a number of non-breaking commits that should be easy to backport to the 19.x branch if we want to make one last release there as well as a 20.0 release.

I'm happy to draft a PR that does this if it makes sense.

**Comment by benoitc** [comment]
@di yes and any help is welcome to make the backport release. I am creating the related branch for it.


About the 20.0 i will create a release  and also clean a little the tickets to make sure it's in phase with future needs :)

**Comment by di** [comment]
I created https://github.com/benoitc/gunicorn/pull/2114 to backport commits from #2022 to the `19.x` branch.

**Comment by benoitc** [comment]
@di thanks! I will merge it over the week-end and do a release.  

I created 2 milestones then and we will have next week 2 releases. Thanks all for the feedback.
