### ISSUE TITLE
Worker does not pick up proper files to watch for reloading when rebooting

### ISSUE THREAD

**Issue by talham7391** [benoitc/gunicorn#2133]
When launching Gunicorn with the `--reload` option, workers will start the Reloader and then load the wsgi app. This is problematic because user files are loaded when the wsgi app is loaded, and the reloader depends on the user files to be loaded so that it can watch them.

So when the Reloader starts, it isn't watching any user files. This isn't an issue when using the default polling reloader as it updates what files it is watching every time it polls but this is an issue with the inotify reloader.

**Comment by trendels** [comment]
The [change in 3054b18](https://github.com/benoitc/gunicorn/commit/3054b184dea1b07581293c203a1c546c7ea3ebca) broke  the default reloader unfortunately. When a file has a syntax error, gunicorn now crashes when reloading, with this exception:

```
Traceback (most recent call last):
  File "/home/st/gunicorn_reload_test/venv/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/st/gunicorn_reload_test/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/home/st/gunicorn_reload_test/venv/lib/python3.7/site-packages/gunicorn/workers/base.py", line 160, in load_wsgi
    self.reloader.add_extra_file(exc_val.filename)
AttributeError: 'NoneType' object has no attribute 'add_extra_file'
```
The reason is that `load_wsgi()` calls `self.reloader.add_extra_file()` [here](https://github.com/benoitc/gunicorn/blob/master/gunicorn/workers/base.py#L158). The commit linked above moved the initialization of `self.reloader` after the call to `load_wsgi()`, so it is not properly initialized.

**Comment by tilgovi** [comment]
@trendels I'm truly sorry I missed that in my reviews. I've opened #2248. Feel free to pick up the issue yourself, if you're so inclined, and I'm happy to review. I'll try to make time before our next release, if you cannot.

**Comment by trendels** [comment]
@tilgovi thanks for creating the issue. I have a fix ready but I'm still figuring out how to write a good test for it. I'll make a pull request later today.
