### ISSUE TITLE
Demistify python version support

### ISSUE THREAD

**Issue by waghanza** [benoitc/gunicorn#2149]
Hi @benoitc @tilgovi,

The `README` says (in **installation** section) that `gunicorn` requires `python` **3.4** (at least) to run
https://github.com/benoitc/gunicorn#installation

However, the badge on the same `README` says that `gunicorn` runs for `python` **2.6** to **3.6**.

According to my tests, I have successfully runs on  `python` **3.8**.

Could we officially adds support for `python` **3.4** to **3.8** ?

Regards,

PS : I do not know which version of `python` use `gunicorn`'s users

**Comment by dom-nie** [comment]
Hi @waghanza 

README is correct, however README is generated from github branch while badge is generated from latest PyPI release, where supported versions included **2.6, 2.7, 3.2, 3.3, 3.4, 3.5, 3.6** which makes it correct.

Badge will be updated with **20.0.0** release, since current release is from `July 2018` it's no wonder that list is outdated.

Currently only python **3.4** to **3.8** is supported on master branch.

I hope this explains your confusion.

**Comment by waghanza** [comment]
ah, ok. Thanks for this explanations
