### ISSUE TITLE
Timeout using gevent working mode

### ISSUE THREAD

**Issue by hiluyu** [benoitc/gunicorn#2246]
你好，我在使用中遇到一个问题。在大镜像转换格式中，进程被kill。查看日志后时gunicorn超时。
请问，1、gunicorn超时是从哪里开始计时的。2、使用gevent工作模式，还是超时。

Hi, I'm having a problem with it.In the large image conversion format, the process is killed.Gunicorn timed out after viewing the log.
1. Where did the gunicorn timeout start? 2. Use gevent working mode or timeout.

**Comment by benoitc** [comment]
Sorry for the delay to answer. Timeout happen when a worker failed to notify the arbiter in time. In your case it probably happened because your image conversion process is ttaking too much time and is bvlocking. You should make sure to iterate this conversion in small steps and go back to gevent loop between these steps.
