### ISSUE TITLE
Get number of workers, dynamic update worker count. 

### ISSUE THREAD

**Issue by joey-mcadams** [benoitc/gunicorn#2270]
Is there a way via the API in Python to get the number of workers and/or dynamically update the number of workers? 

We're running a custom implementation and passing a Flask app to Gunicorn in python. 

The issue I'm having is I can update workers using Linux signals to the master process. However, that feels kind of hacky. I tried getting at the Arbiter at run time, but it doesn't seem to sync properly with all the workers 

```
arbiter = Arbiter(self) 
```
I've tried that code in init(), run(), and in various functions in between to get at the arbiter. It doesn't seem like I can get at that via the base application either `gunicorn.app.base.BaseApplication`

Is there a recommended way to update threads and workers in python, not via the command line?

**Comment by benoitc** [comment]
> The issue I'm having is I can update workers using Linux signals to the master process. However, that feels kind of hacky.

This is not hacky at all and why signals are existing. IMO that the simpler way to operate gunicorn. 

You can get the number of worker in one arbiter hook using the WORKERS property of the arbiter.  but that not recommended.

**Comment by tilgovi** [comment]
Thanks for the question, @jmcadams-r7. At this time, Gunicorn has no supported public API for custom Python applications beyond that which is documented for [loading custom application configuration](http://docs.gunicorn.org/en/latest/custom.html). Once control is handed to the `Arbiter` class it never returns. Signals are used to interrupt the arbiter. Any other approach would necessitate some additional concurrency support in the arbiter so that user code could instantiate the arbiter and then, later, invoke an API. Supporting such an API would be a big step, but if we can come up with a proposal for how this would work I would give feedback.

Let me know if that answers your question and we can close the issue. If we want to proceed with something more we can open an issue to discuss proposals.
