### ISSUE TITLE
worker_abort not running on timeout

### ISSUE THREAD

**Issue by posix4e** [benoitc/gunicorn#2284]
I added some code to print the traceback when a worker timesout but it doesn't seem to work always.

I'm starting the process with
```
gunicorn -b 0.0.0.0:5000 -c gunicorn_prometheus_conf.py run:app log-file=- --log-level DEBUG
```

My gunicorn_prometheus_conf.py  contains
```
import os

import honey_helpers
import multiprocessing
import traceback

COMPONENT = os.getenv("COMPONENT", "ACCOUNTS").upper()
COUNT = int(os.getenv("WORKER_COUNT", multiprocessing.cpu_count()))

if "development" in os.getenv("APP_SETTINGS", "development") or 'true' in os.getenv(
        "GEVENT", "false").lower():
    # We need 4 workers to support some of our complicated multi
    # request apis
    workers = 2
else:
    # Let's let k8s scale past this
    workers = COUNT


def post_worker_init(worker):
    honey_helpers.pre_honey_app(COMPONENT)


def worker_abort(worker):
    pid = worker.pid
    print("worker is being killed - {}".format(pid), flush=True)
```

For some reason, while I'm locally testing if I sleep long enough to trigger the print. In production on a k8s cluster, I'm not seeing the print. I don't know what's causing these timeouts and assume worker_abort is not being called on timeout. 
In the logs all I see is
```
Mar 3 17:08:10 accounts-756c975868-m5cbk accounts CRITICAL +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:213)
```

I added

```
@admin.route('/timeout', methods=['GET', 'POST'])
def timeout():
    time.sleep(300)
    return "OK"
```
and was able to simulate the timeout and that called worker abort correctly.

it looks like
```
Mar 3 18:33:01 accounts-68bc66fd88-tpwsp accounts CRITICAL +0000] [6] [CRITICAL] WORKER TIMEOUT (pid:87)
Mar 3 18:33:01 accounts-68bc66fd88-tpwsp accounts ERROR gunicorn - ERROR - worker is being killed - 87
Mar 3 18:33:01 accounts-68bc66fd88-tpwsp accounts ERROR ERROR:gunicorn:worker is being killed - 87
  File "/usr/local/bin/gunicorn", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/wsgiapp.py", line 74, in run
    WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 203, in run
    super(Application, self).run()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/app/base.py", line 72, in run
    Arbiter(self).run()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 211, in run
    self.manage_workers()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 544, in manage_workers
    self.spawn_workers()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 611, in spawn_workers
    self.spawn_worker()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/arbiter.py", line 578, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 131, in init_process
    self.run()
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/sync.py", line 124, in run
    self.run_for_one(timeout)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/sync.py", line 68, in run_for_one
    self.accept(listener)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/sync.py", line 30, in accept
    self.handle(listener, client, addr)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/sync.py", line 135, in handle
    self.handle_request(listener, req, client, addr)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/sync.py", line 176, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/beeline/middleware/flask/__init__.py", line 84, in __call__
    return self.app(environ, _start_response)
  File "/usr/local/lib/python3.6/dist-packages/werkzeug/middleware/proxy_fix.py", line 232, in __call__
    return self.app(environ, start_response)
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.6/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/work/web/exchange_api/admin/views.py", line 47, in timeout
    time.sleep(300)
  File "/usr/local/lib/python3.6/dist-packages/gunicorn/workers/base.py", line 191, in handle_abort
    self.cfg.worker_abort(self)
  File "gunicorn_prometheus_conf.py", line 31, in worker_abort
    traceback.print_stack()
Mar 3 18:33:01 accounts-68bc66fd88-tpwsp accounts INFO +0000] [87] [INFO] Worker exiting (pid: 87)
Mar 3 18:33:01 accounts-68bc66fd88-tpwsp accounts INFO +0000] [159] [INFO] Booting worker with pid: 159```

So how am I getting other timeouts which don't stack trace

**Comment by tilgovi** [comment]
I had to do some reading to understand what might be going on here. Let me summarize what I know and end with a couple questions.

The arbiter process sends an abort signal to a worker the first time it sees that a worker has timed out, and a kill signal the second time. This happens in the `murder_workers` method of the arbiter:

https://github.com/benoitc/gunicorn/blob/master/gunicorn/arbiter.py#L486

If the worker has a chance to handle the abort signal, it will call `worker_abort`. The first explanation, then, is that the worker may be killed before it gets a chance to execute `worker_abort`.

If your worker is not getting a chance to run `worker_abort` in production, it may be because the worker is running code when it receives the abort or is under load such that it doesn't get a chance to handle the abort quickly enough. A possible example where a worker would not handle the abort is a worker performing some code in a C extension module that prevents the Python signal handler from running until execution is returned to the interpreter. Contrast this with a `time.sleep()`, which I think would allow the Python signal handler to run.

Another possibility is that we have conditions under which the main arbiter loop does not wait a second between sending abort and sending kill. Under normal conditions, `murder_workers` is called once a second by the main loop of the arbiter:

https://github.com/benoitc/gunicorn/blob/master/gunicorn/arbiter.py#L196

In the absence of any signals, the arbiter sleeps for one second each time through the loop. However, when the process receives a signal, the signal handler appends the signal to a queue, writes to a pipe, and then returns. Upon returning to the main execution context, the arbiter will either notice the signal in the queue. If it was asleep, it will notice the byte on the pipe and wake up, repeating the loop and noticing the signal in the queue. In this way, the arbiter can defer the bulk of the signal handling work to the main execution context, rather than doing it in the signal handler context.

So it seems, perhaps due to signals arriving or a bug in the implementation, that the worker is not given a full second to abort. It does not seem like we went to great lengths to ensure that the loop doesn't repeat quickly and execute the kill before a second has elapsed. In light of this issue, I've raised a couple of questions in IRC that I would love to know answers to and I invite you dig in, if you're so motivated:

> I was just reading over some arbiter code and now I have two questions:
> - Why do we limit the length of the signal queue? Are there risks to doing so? What tradeoff are we making and why? https://github.com/benoitc/gunicorn/blob/master/gunicorn/arbiter.py#L192
> - Why does the arbiter wake itself up at the end of the signal queue handling loop? Isn't it already awake? https://github.com/benoitc/gunicorn/blob/master/gunicorn/arbiter.py#L225

**Comment by Ammadkhalid** [comment]
is it solve? i'm facing issue here. As @tilgovi mentioned. If i use `sleep`, it worked and `worker_abort` is being call. However, Other than this. It's not running `worker_abort` function.

**Comment by tilgovi** [comment]
Yes, it is. I'm not aware of anyone having done any followup investigation on my questions from 2020. However, I did open #2314, which again raises the question of why we have a limit on the length of the signal queue.

**Comment by Chammar37** [comment]
I came across this issue in our nginx/guni/django app. Is relying on worker_exit() a reliable replacement as the worker timeout exit path is: worker_abort() → worker_exit()
