### ISSUE TITLE
Gunicorn running asynchronous workers Python 3.7

### ISSUE THREAD

**Issue by Asturias-sam** [benoitc/gunicorn#2351]
I using this command to run my web server

```
 gunicorn \
      -w 10 \
      -k gevent \
      --timeout 120 \
      -b  0.0.0.0:8088 \
      --limit-request-line 0 \
      --limit-request-field_size 0 \
      --statsd-host localhost:8125 \
      "superset.app:create_app()"
```
I getting the below mentioned error:

```
Error: class uri 'gevent' invalid or not found: 

[Traceback (most recent call last):
  File "/home/s0p04bp/env/lib/python3.7/site-packages/gunicorn/util.py", line 99, in load_class
    mod = importlib.import_module('.'.join(components))
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 726, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/s0p04bp/env/lib/python3.7/site-packages/gunicorn/workers/ggevent.py", line 14, in <module>
    import gevent
  File "/home/s0p04bp/env/lib/python3.7/site-packages/gevent/__init__.py", line 98, in <module>
    from gevent.os import fork
  File "/home/s0p04bp/env/lib/python3.7/site-packages/gevent/os.py", line 495, in <module>
    _raw_posix_spawnp = os.posix_spawnp
AttributeError: module 'os' has no attribute 'posix_spawnp'

```

This is because of this parameter `-k gevent` if i remove this then it's working fine.
How to make Gunicorn run asynchronous ?

**Comment by jamadden** [comment]
The error is because gevent is not compatible with your platform. 

It's an interesting error because it means your `os` module has `posix_spawn`, but *not* `posix_spawnp`. I didn't know that was possible (I'm the gevent maintainer). According to [the documentation](https://docs.python.org/3.9/library/os.html#os.posix_spawn) those two attributes were added to Python 3.8, but the paths in your output include `python3.7`, making it look like you're running on Python 3.7. But Python 3.7 doesn't have `posix_spawn`.  Can you tell us about your platform, and how you got a `posix_spawn` attribute on the `os` module? 

Until/Unless we get that compatibility issue solved, you'll have to choose a different gunicorn worker type.

**Comment by som2014** [comment]
@jamadden Thanks for the info but i am not sure `posix_spawn` about adding into python 3.7.
I am solving this error for past few days so might run some commands.

For Gunicorn what worker type should be using where each request generates an I/O-bound database query in Superset. basically  require a dynamic output.

**Comment by jamadden** [comment]
Well, `posix_spawn` is the root of your trouble. If you can figure out why you have that when you're not supposed to, there might be something we can do. 

Alternatively, you could upgrade to Python 3.8 which should provide the missing function.

Normally, if you have gevent-compatible database drivers I would suggest using the gevent worker. But if you don't, or if you can't figure out what's different about your `os` module, your choices are limited. You can try the eventlet or threaded workers.

**Comment by benoitc** [comment]
closing issue as answered.
