### ISSUE TITLE
Why Gunicorn is not utilizing full resource ?

### ISSUE THREAD

**Issue by shreeraj04** [benoitc/gunicorn#2395]
Ubuntu - 8core/16 GB RAM/CPU
Gunicorn version: 19.7.1
Python version: 3.7.8

I am sending 500 concurrent requests. I am monitoring the CPU and it is not crossing 44%. Why it is not taking the resource when its available ?
When I tried the same with 4 core/8GB/CPU system it was taking 98% CPU for the same number requests.

Kindly let me know the issue and resolution for the same. Thanks in advance.

**Comment by jamadden** [comment]
The answer is that it depends on a lot of things. How do have gunicorn configured (how many workers, and of what type)? What kind of requests are you making, and how does your application handle them?

Note that high CPU usage isn't necessarily a good thing, nor is it necessarily a measure of the system's ability to process additional requests. It's possible, for example, for a system to be IO bound before it is CPU bound; that's why things like gevent and asyncio exist in the first place. It's also possible for a system to not scale vertically, for example, due to contention over locks. In both cases, CPU usage can plateau because the process is spending all of its time waiting on events to happen.

**Comment by shreeraj04** [comment]
Thank you for your response.
I've configured Gunicorn to use "2*no. of cores+1". Tried by doubling it as well. 
The requests basically contains 1 image base64 string and an uniqueID. The face encoding is taken from this base64 string and finding the comparison with another image where its encoding is predefined.

Using the face_recognition module to find the face distance between 2 faces. Here, I am not writing any images to the disk. 
The application is written in Python aiohttp which uses worker-class=aiohttp.GunicornWebWorker.

**Comment by benoitc** [comment]
it will depends on your OS scheduler but also the scheduler used by this async libraries and especially the number of threads used by their eventloop. You should make sure to put any blocking work outside of the GIL also (like in a thread, a separate process) if you want to max out your machines.
