### ISSUE TITLE
Workers auto Killed frequently .

### ISSUE THREAD

**Issue by sarkaramal** [benoitc/gunicorn#2420]
I have a gunicorn service with 10workers running the TensorFlow app on GCP. The services get killed frequently. 
There is no log why It gets killed. Can someone help with this?

**Comment by benoitc** [comment]
if it says timeout it's because your request is taking to much time. A good practice for it is to not launch your machine learning process in a web context but outside of it and only dedicate the web app to display results and/or statuses of the ml request. This is also better in term of resource management.
