### ISSUE TITLE
How to pass argparse via gunicorn python

### ISSUE THREAD

**Issue by nguyentthai96** [benoitc/gunicorn#2423]
I have application flask run with terminal as 
`python server_api_predict.py -mf /home/user/Desktop/ParlAI/model/blender/blender --inference beam` runing OK
But, I want to config with gunicorn 
` wsgi:app -mf="/home/user/Desktop/ParlAI/model/blender/blender" --inference="beam" -k gevent --worker-connections 1000 --preload` --> it is wrong `Parse Error: unrecognized arguments:`
I have reading some gui as 
`gunicorn 'wsgi:app(-mf="/home/user/Desktop/ParlAI/model/blender/blender" --inference="beam")' -k gevent --worker-connections 1000 --preload` but I don't understand.
in source have self.args = super().parse_args(args=args) read argument python command line
![image](https://user-images.githubusercontent.com/14333403/93365257-c21f9a80-f873-11ea-9f26-79dedf16ee0e.png)

What solution pass argparse with gunicorn, thank you.

**Comment by nguyentthai96** [comment]
Hello, If not function, I can request a feature??
Thank you!

**Comment by benoitc** [comment]
Due to the [design](https://docs.gunicorn.org/en/stable/design.html) of Gunicorn, passing arguments like it is not the supported way. You have to pass environments cariables that will be given to each workers handling the WSGI application:

https://docs.gunicorn.org/en/stable/settings.html#raw-env

like `--env mf=/home/user/Desktop/ParlAI/model/blender/blender --env inference=beam ....` then use os.environ to get it in your app or add a thin layer to make it available as an argparse instance.

**Comment by benoitc** [comment]
I assume the response was read since, so closing the issue.
