### ISSUE TITLE
ModuleNotFoundError: No module named 'django.core.asgi'

### ISSUE THREAD

**Issue by AJS-KZ** [benoitc/gunicorn#2461]
File "/code/project/asgi.py", line 12, in <module>
web_1     |     from django.core.asgi import get_asgi_application
web_1     | ModuleNotFoundError: No module named 'django.core.asgi'
web_1     | [2020-11-22 15:55:39 +0000] [9] [INFO] Worker exiting (pid: 9)
web_1     | [2020-11-22 15:55:39 +0000] [10] [ERROR] Exception in worker process
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
web_1     |     worker.init_process()
web_1     |   File "/usr/local/lib/python3.7/site-packages/uvicorn/workers.py", line 55, in init_process
web_1     |     super(UvicornWorker, self).init_process()
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 119, in init_process
web_1     |     self.load_wsgi()
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
web_1     |     self.wsgi = self.app.wsgi()
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
web_1     |     self.callable = self.load()
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
web_1     |     return self.load_wsgiapp()
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
web_1     |     return util.import_app(self.app_uri)
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/util.py", line 358, in import_app
web_1     |     mod = importlib.import_module(module)
web_1     |   File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
web_1     |     return _bootstrap._gcd_import(name[level:], package, level)
web_1     |   File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
web_1     |   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
web_1     |   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
web_1     |   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
web_1     |   File "<frozen importlib._bootstrap_external>", line 728, in exec_module
web_1     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
web_1     |   File "/code/project/asgi.py", line 12, in <module>
web_1     |     from django.core.asgi import get_asgi_application
web_1     | ModuleNotFoundError: No module named 'django.core.asgi'
web_1     | [2020-11-22 15:55:39 +0000] [10] [INFO] Worker exiting (pid: 10)
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 209, in run
web_1     |     self.sleep()
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 357, in sleep
web_1     |     ready = select.select([self.PIPE[0]], [], [], 1.0)
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
web_1     |     self.reap_workers()
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
web_1     |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
web_1     | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
web_1     | 
web_1     | During handling of the above exception, another exception occurred:
web_1     | 
web_1     | Traceback (most recent call last):
web_1     |   File "/usr/local/bin/gunicorn", line 8, in <module>
web_1     |     sys.exit(run())
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/wsgiapp.py", line 58, in run
web_1     |     WSGIApplication("%(prog)s [OPTIONS] [APP_MODULE]").run()
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 228, in run
web_1     |     super().run()
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/app/base.py", line 72, in run
web_1     |     Arbiter(self).run()
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 229, in run
web_1     |     self.halt(reason=inst.reason, exit_status=inst.exit_status)
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 342, in halt
web_1     |     self.stop()
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 393, in stop
web_1     |     time.sleep(0.1)
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 242, in handle_chld
web_1     |     self.reap_workers()
web_1     |   File "/usr/local/lib/python3.7/site-packages/gunicorn/arbiter.py", line 525, in reap_workers
web_1     |     raise HaltServer(reason, self.WORKER_BOOT_ERROR)
web_1     | gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
domme_backend_web_1 exited with code 1

Hello every one

Who can help with this error?

**Comment by jamadden** [comment]
You need to install whatever package provides `django.core.asgi` in such a way that it's on `sys.path` when you run `gunicorn`.

You appear to have installed `gunicorn` in the main site-packages directory of your Python installation (`/usr/local/lib/python3.7/site-packages`), so you could install whatever provides `django.core.asgi` in the same way and same place. For example, you might write `/usr/local/bin/python3.7 -mpip install <SOME PACKAGE>`. 

(Instead of installing both gunicorn and all your dependencies directly in your Python installation, however, I would recommend the use of a virtualenvironment, especially during development.)

Alternately, you may wish to set the PYTHONPATH environment variable for the `gunicorn` process.

Keep in mind that if you installed your dependencies using pip's `--user` flag, and you are now trying to run gunicorn as a different user account (for example, as a service), anything installed that way for the first user won't be available to the user running the service.

For more information, check out the documentation for `pip`, `virtualenv` or the `venv` module from the standard library, the general Python documentation for package management, or your operating system's documentation for Python package management.
