### ISSUE TITLE
Why was APP_MODULE changed to WSGI_APP

### ISSUE THREAD

**Issue by thenewguy** [benoitc/gunicorn#2519]
Since there is ASGI and WSGI, it is slightly confusing to call the configuration file option `wsgi_app` instead of `app_module` or `app` or something generic.  Unless there are also plans to add `asgi_app` for automatically picking the correct worker I guess.

I came searching for how to specify the asgi app in the config file while preparing to use [uvicorn for my worker_class](https://www.uvicorn.org/) and found PR #1450.  Figured I would raise the issue for a future improvement as ASGI becomes more common

**Comment by tilgovi** [comment]
Before that PR there was no `wsgi_app` option in the config, it was only a positional argument on the command line that happened to be called `APP_MODULE` in the usage documentation. Now that this does exist in the configuration file, it's probably not worth changing unless we hear that it's very confusing, since that will cause any existing use in config files to break. If you think we should add an alias, that can be done without backwards incompatibility, maybe.
