### ISSUE TITLE
Request blocked using worker_class=gevent (Flask App)

### ISSUE THREAD

**Issue by statfs** [benoitc/gunicorn#2525]
I just create a ThreadExecutorPool in worker, it seems very strange because request blocked.

Flask App below:

```
from flask import Flask    
app = Flask(__name__)

from concurrent.futures import ThreadPoolExecutor
executor = ThreadPoolExecutor(2)

@app.route('/')
def hello_world():
    hw = "Hello world! " + threading.currentThread().getName()
    print(hw)
    executor.submit(func)
    return hw

import time
import threading
def func():
    print("envoke thread: " + threading.currentThread().getName())
    start = time.time()
    while 1:
        end = time.time()
        if end - start > 3:
            print("jump out of thread:" + threading.currentThread().getName())
            break
```

It works when start the app with 
```
gunicorn app:app -k sync -w 2 -b 0.0.0.0:8888
```
Test like this.
```
$time curl localhost:8888
Hello world! MainThread
real    0m0.022s
user    0m0.003s
sys     0m0.006s
```

If I change sync to gevent, the requests will be blocked.

```
gunicorn app:app -k gevent -w 2 -b 0.0.0.0:8888
```
Test results: 
```
$time curl localhost:8888
Hello world! Dummy-1
real    0m3.017s
user    0m0.005s
sys     0m0.005s
```

any advice?

**Comment by jamadden** [comment]
When using the gevent worker, the system is [monkey-patched to work with gevent](http://www.gevent.org/intro.html#monkey-patching). That means that `ThreadPoolExecutor` uses greenlets, not native threads.

Your `func` just spins the CPU in a tight loop and [does not cooperate with the gevent event loop](http://www.gevent.org/intro.html#cooperative-multitasking). That's a long way of saying that *nothing else gets to run* while `func` is running. 

There are two options. The first is to write `func` to cooperate with gevent and let other things run; e.g., instead of spinning the CPU for 3 seconds in a tight loop, just call `time.sleep(3)` — that's better even when *not* running with gevent.

The second option is to use an API that runs `func` in a native thread. The simplest way to do that would be to change `from concurrent.futures import ThreadPoolExecutor` to [`from gevent.threadpool import ThreadPoolExecutor`](http://www.gevent.org/api/gevent.threadpool.html#gevent.threadpool.ThreadPoolExecutor).

**Comment by statfs** [comment]
Many thanks.
Actually the "while 1" emulates the CPU intensive workload, like numpy.

It seems that gunicorn(gevent) will dispatch more than once or block many requests, when the worker CPU 100% running. But worker class = sync behave normal.
