### ISSUE TITLE
Supervisor can't find command gunicorn on venv ( Virtual Enviroment)

### ISSUE THREAD

**Issue by animax1991** [benoitc/gunicorn#2575]
I had followed this tutorial series to deploy the Flask example: https://youtu.be/goToXTC96Co?t=3907

Everything is working fine until this step: Supervisor (starting from 1:05:42 of the video). I got this error: can't find command '/home/animax/Flask_Blog/venv/bin/gunicorn'.

I try to locate the gunicorn on venv/bin but nothing found. So where is gunicorn located? I think supervisor can't find the gunicorn.

When I use "Whereis gunicorn", it give me this location: "gunicorn: /home/animax/.local/bin/gunicorn". Why Gunicorn is here but not on venv?

My flaskblog.conf of Supervisor:

[program:flaskblog]
```
directory=/home/animax/Flask_Blog
command=/home/animax/Flask_Blog/venv/bin/gunicorn -w 3 run:app
user=animax
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/flaskblog/flaskblog.err.log
stdout_logfile=/var/log/flaskblog/flaskblog.out.log
```

It took me nearly 2 days for researching online but still can't fix it. So I think I should ask help here. Thank you!

**Comment by jamadden** [comment]
I can't watch over an hour of a video to try to understand what went wrong. It would be easier if you would just post the text transcript of the commands you enter in your terminal; then we could see what happened and try to reproduce it ourself. 

That said, this has *nothing to do with gunicorn*. This is just normal Python package installation. I can guess at what might have gone wrong.

The directory `~/.local/bin` is used for commands when you explicitly request it with `pip install --user`, as `pip install --help` points out:
```console
pip install --help  | grep \\.local
  --user    Install to the Python user install directory for your platform. Typically ~/.local/, or %APPDATA%\Python on Windows. (See the Python documentation for site.USER_BASE for full details.)
```

Don't do that if you arer working in a virtual environment.

`pip` will also automatically use a `--user` installation if the normal directory isn't writable. It will warn you about this repeatedly (I'm on a mac, so my path isn't `~/.local` but something else):
```console
$ /opt/local/bin/python -m pip install gunicorn
Defaulting to user installation because normal site-packages is not writeable
Collecting gunicorn
  Using cached gunicorn-19.10.0-py2.py3-none-any.whl (113 kB)
Installing collected packages: gunicorn
  WARNING: The scripts gunicorn and gunicorn_paster are installed in '/Users/.../Library/Python/.../bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
```

Why would the normal directory not be writable? Above, I specifically used a system Python installation, *not* one from a virtual environment; usually, system Python installations can't be modified by normal users. So, if you didn't have your virtual environment active, or you didn't specify the proper path to `pip` or `python` when you installed gunicorn, you may have accidentally used a system Python to install gunicorn instead of the Python in your virtual environment.

In either case, the fix is simple: Just install gunicorn using the correct `pip` from your virtual environment. (You may need to uninstall the version installed in `~/.local/` first.)

**Comment by animax1991** [comment]
Thanks for quick response!

I have the same issue with this topic but can't solve. Please help!

https://github.com/benoitc/gunicorn/issues/1588

when I use this command with "sudo supervisorctl reload"

Then the error message in the status

```
File "/home/nhcc/.local/bin/gunicorn", line 7, in
from gunicorn.app.wsgiapp import run
ImportError: No module named 'gunicorn'
```

**Comment by jamadden** [comment]
(You probably shouldn't be running gunicorn as root.)

That's basically the same problem as this one. Note that error message still points to a local user copy of `gunicorn`. Fix that problem, then be sure you are invoking the right `supervisorctl`.
