### ISSUE TITLE
max_requests customized behaviour

### ISSUE THREAD

**Issue by gautamsinghania95** [benoitc/gunicorn#2602]
* I am using `max_requests` for limiting memory leaks.
* I have a ping API used by Kubernetes cluster to check pod health
* I want to avoid this ping API in request count
* I also want to understand how `timeout` and `graceful_timeout` work with `max_requests`
* Is there a way to tell Gunicorn to **NOT** force-kill a worker after restart signal was sent?

**Comment by benoitc** [comment]
there is no reason to remove the ping from the request count since it's measure the health for your system. Why not fixing the memory leaks if you know they exist? `max_requests` should really be seen as temporary workaround.

Anyway, there may be a way to achieve what you want using the hooks. On pre or post request you can look at the e request and have access to the request counter in the worker instance. So it should be possible to decrease it when a ping is received.

`timeout`, `graceful_timeout` are independent mechanisms and are not aware of the `max_requests` setting.

**Comment by gautamsinghania95** [comment]
> there is no reason to remove the ping from the request count since it's measure the health for your system. 
The usecase for `max_requests` (even genuine usecases) might sometime want to avoid certain APIs like pings. Seems to me like a genuine usecase, and you might want to consider adding a config for this.

> Why not fixing the memory leaks if you know they exist? `max_requests` should really be seen as temporary workaround.
Memory leaks are caused by external Python libraries that we need to use

> Anyway, there may be a way to achieve what you want using the hooks. On pre or post request you can look at the e request and have access to the request counter in the worker instance. So it should be possible to decrease it when a ping is received.
Thanks for the workaround, I will look into this :)

> `timeout`, `graceful_timeout` are independent mechanisms and are not aware of the `max_requests` setting.
I would have thought that when restarting a worker after `max_requests` have been achieved, these settings would be used to control restart behaviour. If that is not the case, then does the worker get immediately restarted?

**Comment by ufou** [comment]
I'm also interested to know what happens to an established request when `max_requests` is reached and workers are restarted - surely there must be a timeout, otherwise a request might keep the worker alive for a very long time?

**Comment by ufou** [comment]
also to note `uWSGI` has a similar feature for max worker requests but also has a specific value for timeout after which a worker is forcibly killed, eg: `worker-reload-mercy = 60`
