### ISSUE TITLE
gunicorn breaks django authentication within container

### ISSUE THREAD

**Issue by bholland** [benoitc/gunicorn#2658]
Hello all,

I have the latest versions of gunicorn and django. I set up and configured the django authorization (django.contrib.auth) and it stores sessions correctly in the database and cookie. I test this system in run_server and it works as intended. 

I then build a docker container with gunicorn running on port 8050 like so:

exec gunicorn DataManagement.wsgi:application \
    --name=DataManagement \
    --workers=4 \
    --log-level=debug \
    --bind=0.0.0.0:8050 \
    --timeout=600 \
    --log-file=./gunicorn.log \
    --log-level=debug \
    --worker-class=gthread \
    --keep-alive=600

The worker class and keep alive were added to try and debug this issue to no effect. My docker-compose file exposes port 8050 and routes 0.0.0.0:8050:8050. 

The session login system within django does not work. I will log in and 80% to 90% of the time and it will not authenticate. If I have a login_required decorator around a view, it will cycle the login page until it succeeded in a 1 in 10 chance. It will eventually succeed. I have examined the request headers and nothing seems to differ between the gunicorn and run_server request headers or contents. 

Originally I had this connected via nginx to reverse proxy to gunicorn but to test it out I just go to http://mysite.com:8050/accounts/login/ and it fails over and over but will randomly succeed. 

Given that this works with the django run_server command, it likely isn't my configuration. Given that it happens on port 80 and 8050, it doesn't appear to be nginx. So that leaves gunicorn. What is happening inside of my docker container where gunicorn breaks session information in django requests?

**Comment by jamadden** [comment]
gunicorn works at a much lower level than sessions and authentication, so it's unlikely to be gunicorn itself. At a guess, based on your statement that it sometimes works, I would say it has to do with the number of workers (meaning there's some per-process state). Have you tested with a single worker? 

Have you tested with other WSGI servers inside your container (which aren't multi-worker)? You could try [`gevent.pywsgi <app>`](https://github.com/gevent/gevent/blob/master/src/gevent/pywsgi.py#L1579). [waitress](https://pypi.org/project/waitress/) is a well-known WSGI server that's multi-threaded.

**Comment by bholland** [comment]
You are right. It is the workers. My guess is that with 4 workers, it will
distribute my connection but in different process. Within different process
it can't save state. 1 worker worked fine. I don't have a solution to this
issue though and I still think it is a bug. It should also be something
everyone can repete.

**Comment by jamadden** [comment]
This is **not** a bug in gunicorn; distributed multi-processes are what gunicorn *does*. 

If there's a bug, it's in the application or web framework, assuming they're meant to be used in multiple processes in the first place. If they're not meant to be used in multiple processes, that's a design decision. Either way, it's got nothing to do with gunicorn.

**Comment by bholland** [comment]
Now there I have to disagree. I expect gunicorn to handle django authentication across workers. It does not do that.  In fact, this creates such an impossible situation that it took days of debugging to figure out that the problem was gunicorn. This occurs across various worker types as well.  Unless you demand this falls onto django or I shouldn't use gunicorn to serve the pages because it simply won't work with the standard django authentication system.

**Comment by jamadden** [comment]
gunicorn sits *below* django. It's **only** a WSGI server. It has literally nothing to do with django. 

Because I don't use django, I can't offer you advice on making django authentication work with multiple workers, you'll have to look elsewhere for that (as a start, perhaps examine your configuration looking for references to "in memory;" obviously that won't work and you'll need a "persistent" or "stateless" configuration). Because any production system at scale is likely going to use multiple workers, whether on a single machine or across a cluster of machines, django surely must have a way to let its authentication be distributed in this way; you'll just have to find it.

And yes, you probably could use one threaded worker on a single machine. If your load is low enough, that may be sufficient for you (it also depends on your application).

Good luck!

**Comment by zjttoefs** [comment]
While this indeed has nothing to do with gunicorn, this issue comes up when looking for clues. So I'd like to provide a solution here. I came across the same problem and the root cause was
`SESSION_ENGINE = "django.contrib.sessions.backends.cache"`
That only stores the session information in the individual backend process. If you set this to one of 
* django.contrib.sessions.backends.cached_db
* django.contrib.sessions.backends.file
* django.contrib.sessions.backends.signed_cookies
authentication works fine as sessions are shared between workers.
