### ISSUE TITLE
How to distribute evenly tasks to multiple worker?

### ISSUE THREAD

**Issue by wawashi** [benoitc/gunicorn#2670]
Hi,

We want to run multiple asynctask at the same time with gunicorn + uvicorn.

We tried 5 tests that 100 tasks were given to 5 async worker at the same time.
We got the result as shown in the table below that the number of tasks which each process has was biased. (test2, test3)
What should we do for stable distribution of the number of tasks?

`gunicorn main:app -w 5 -k uvicorn.workers.UvicornWorker`

We are using the gunicorn defalut settings.

  | test1 | test2 | test3 | test4 | test5
-- | -- | -- | -- | -- | --
process1 | 21 | 3 | 96 | 20 | 3
process2 | 34 | 1 | 4 | 19 | 23
process3 | 0 | 86 | 0 | 20 | 23
process4 | 20 | 4 | 0 | 21 | 24
process5 | 25 | 4 | 0 | 20 | 27

Thanks,

**Comment by benoitc** [comment]
requests are processed when a request is handled. So any worker racing  for a  new client to handle will take it if it's in the system queue. You may want to play witht he way the kernel scheduler is handling the process scheduling to fix it. Otherwise there is no way to ensure the distribution will be even between workers.
