### ISSUE TITLE
Client sees connection resets and connection failures on multiple concurrent requests on amazon linux and macos

### ISSUE THREAD

**Issue by rusiaaman** [benoitc/gunicorn#2698]
On 200 concurrent requests, some fail after 20-60 seconds with either "curl: (7) Failed to connect to localhost port 8080: Operation timed out" or "curl: (56) Recv failure: Connection reset by peer" on Amazon Linux (Version 2) and Mac OS (11.4). I don't see any errors when the server runs on Ubuntu 18.

Corresponding errors in python clients are NewConnectionError or ConnectionResetError or RemoteDisconnected error. 

---
To reproduce:

```
Python 3.7.10
gunicorn (version 20.1.0)
Flask 1.0.2
Amazon Linux (Version 2) or Mac OS (11.4) but not Ubuntu 18
```
test.py
```
from flask import Flask
from time import sleep
 
app = Flask(__name__)
 
@app.route('/', methods=["GET"])
def hello_world():
    sleep(10)
    print("DONE")
    return 'Hello World'

```

Gunicorn command `gunicorn --bind 0.0.0.0:8080 --access-logfile - --error-logfile - --level DEBUG test:app`

Create 200 concurrent clients
`for i in {1..200} ; do curl -X GET http://localhost:8082/  >/dev/null 2>&1 & done`

Some of the processes will end with either "Exit 7" or "Exit 56"

Additional notes:
1. The sync worker doesn't time out
2. No error/warning logs from gunicorn, nothing stands out in the output of the gunicorn command.
3. Changing sleep in test.py to 1 second leads to all requests passing but the errors happen for 2 seconds and 3 seconds.
4. On changing from 200 concurrent to 100 no errors happen.

**Comment by jamadden** [comment]
You don't actually ask any question here, so I'm guessing that you're just curious about what's going on.

Most likely, you're seeing an interaction between the listening (server) socket [backlog](https://docs.gunicorn.org/en/latest/settings.html#backlog) and various (and differing) default timeouts in the TCP stacks and maybe even in curl. You can check this with a tool like `netstat`.

The default backlog of 2048 lets all the clients (whether 200 or 100) establish their connection to the server, but they just sit in a queue and wait to be processed one at a time (since a single sync worker can only process one at a time). That looks like this (note that all the sending sockets have 78 bytes of HTTP headers waiting to be read by the server):
```console
$ netstat -n
Active Internet connections
Proto Recv-Q Send-Q  Local Address          Foreign Address        (state)
tcp4      78      0  127.0.0.1.8080         127.0.0.1.50879        ESTABLISHED
tcp4       0      0  127.0.0.1.50879        127.0.0.1.8080         ESTABLISHED
tcp4      78      0  127.0.0.1.8080         127.0.0.1.50878        ESTABLISHED
tcp4       0      0  127.0.0.1.50878        127.0.0.1.8080         ESTABLISHED
tcp4      78      0  127.0.0.1.8080         127.0.0.1.50877        ESTABLISHED
tcp4       0      0  127.0.0.1.50877        127.0.0.1.8080         ESTABLISHED
tcp4      78      0  127.0.0.1.8080         127.0.0.1.50876        ESTABLISHED
tcp4       0      0  127.0.0.1.50876        127.0.0.1.8080         ESTABLISHED
tcp4      78      0  127.0.0.1.8080         127.0.0.1.50875        ESTABLISHED
…
```

Eventually the client or the networking stack times out, `curl` notices this, and exits. Because the connections are established, and since we haven't told curl otherwise, we have to wait for the TCP idle timeouts to kick in. This can vary by system and network path, and actually on my (customized macOS) system, all 200 connections complete normally, though it takes 33:20s (exactly as expected: 200*10/30 = 33 1/3).

If I add `--backlog 1` to the gunicorn command line, the operating system will only let two concurrent connections be opened to the server at once: one it's actively handling, and one in the queue. That looks like this:
```console
$ netstat -n
Active Internet connections
Proto Recv-Q Send-Q  Local Address          Foreign Address        (state)
tcp4       0      0  127.0.0.1.51486        127.0.0.1.8080         SYN_SENT
tcp4       0      0  127.0.0.1.51485        127.0.0.1.8080         SYN_SENT
tcp4       0      0  127.0.0.1.51484        127.0.0.1.8080         SYN_SENT
tcp4       0      0  127.0.0.1.51483        127.0.0.1.8080         SYN_SENT
tcp4       0      0  127.0.0.1.51482        127.0.0.1.8080         SYN_SENT
tcp4       0      0  127.0.0.1.51481        127.0.0.1.8080         SYN_SENT
tcp4       0      0  127.0.0.1.51480        127.0.0.1.8080         SYN_SENT
…
tcp4      78      0  127.0.0.1.8080         127.0.0.1.51129        ESTABLISHED
tcp4       0      0  127.0.0.1.51129        127.0.0.1.8080         ESTABLISHED
tcp4       0      0  127.0.0.1.8080         127.0.0.1.51127        ESTABLISHED
tcp4       0      0  127.0.0.1.51127        127.0.0.1.8080         ESTABLISHED
```

No extra connections are accepted, and the clients time out much faster (SYN timeouts. On my macOS machine, but where I have customized many of the network settings, this latter example takes just 40s:
```console
$ for i in {1..200} ; do curl -X GET http://localhost:8080/ >/dev/null 2>&1 & done; time wait
[1] 20307
[2] 20308
[3] 20309
…
[1]   Done                    curl -X GET http://localhost:8080/ > /dev/null 2>&1
[2]   Done                    curl -X GET http://localhost:8080/ > /dev/null 2>&1
[3]   Done                    curl -X GET http://localhost:8080/ > /dev/null 2>&1
[4]   Exit 28                 curl -X GET http://localhost:8080/ > /dev/null 2>&1
[5]   Exit 28                 curl -X GET http://localhost:8080/ > /dev/null 2>&1
…
[9]+  Done                    curl -X GET http://localhost:8080/ > /dev/null 2>&1

real	0m39.915s
user	0m2.846s
sys	0m4.875s
```

Similarly, we can force `curl` to a specific timeout using the `-m` option. Using the default 2048 backlog:
```console
$ for i in {1..200} ; do curl -m 15 -X GET http://localhost:8080/ >/dev/null 2>&1 & done; time wait
[1] 24005
[2] 24006
[3] 24007
[4] 24008
[5] 24009
[6] 24010
…
[1]   Exit 28                 curl -m 15 -X GET http://localhost:8080/ > /dev/null 2>&1
[2]   Exit 28                 curl -m 15 -X GET http://localhost:8080/ > /dev/null 2>&1
[3]   Done                    curl -m 15 -X GET http://localhost:8080/ > /dev/null 2>&1
[5]   Exit 28                 curl -m 15 -X GET http://localhost:8080/ > /dev/null 2>&1
[4]   Exit 28                 curl -m 15 -X GET http://localhost:8080/ > /dev/null 2>&1
…
real	0m16.192s
user	0m2.617s
sys	0m4.528s
```

My version of `curl` documents exit code 28 as "Operation timeout. The specified time‐out period was reached according to the conditions," code 7 as "Failed to connect to host" and code 56 as "Failure in receiving network data." The exact error will depend on what the underlying operating system surfaced from the TCP stack.

**Comment by rusiaaman** [comment]
Hey @jamadden thanks for the insights. 

Apologies for not making my concern clear. My question was whether it's a bug or expected behavior. In our production system, we have gunicorn behind a load balancer and I see connection resets and closes without response. (Load balancer timeout is much higher than the error times) due to the issue.

> we have to wait for the TCP idle timeouts to kick in

I may be wrong, but unfortunately, it doesn't look like TCP timeout is being reached. Here's some of the relevant output from `sysctl net.inet.tcp` from my mac. Please do let me know if any other setting affects this.

```
net.inet.tcp.keepinit: 75000 # timeout for establishing syn (ms)
net.inet.tcp.keepidle: 7200000 # keepalive idle timer 
net.inet.tcp.keepintvl: 75000
net.inet.tcp.always_keepalive: 0
```

I've also checked the output from `tshark` and it looks like RST is being sent from the server. Here are all the logs from one such tcp stream.

```
1078	1.042688	::1	::1	TCP	88	57131 → 8083 [SYN] Seq=0 Win=65535 Len=0 MSS=16324 WS=64 TSval=73589740 TSecr=0 SACK_PERM=1
1081	1.042708	::1	::1	TCP	64	8083 → 57131 [RST, ACK] Seq=1 Ack=1 Win=0 Len=0
```

Checking the output of `netstat -n` it looks like some of the connections are in SYN_SENT state before closing. This is similar to the output you share after setting `--backlog 1` but in my case, the backlog is left to be the default. Again the error code is `curl: (7) Failed to connect to localhost port 8080: Operation timed out` 

I'm not sure why you're unable to reproduce on your mac, and I am not sure what else to do to make it more reproducible. It looks like the issue is affected by the source os type even when using docker, so the same docker image in ubuntu doesn't have this problem but on Amazon Linux it does, making it hard to reproduce. 

If it still looks like an expected behavior please let me know.

**Comment by jamadden** [comment]
As far as I can tell, this is expected behaviour, differing according to system and network configuration. (And yeah, that's a pain to track down.)

You're right, I should have quoted "TCP idle timeouts" because it was very hand-wavey; I didn't just mean according to the TCP spec, or according to one particular machine. Both client and server and anything layer 3 or above in between them (load balancers, NATs, proxies, certain types of switches, etc) can influence this.

I can't reproduce this on my mac (11.6.1) with up to 300 clients using curl 7.80.0 and the same version of gunicorn (on Python 3.10, though it's not obvious why that would matter). I'm also just using a trivial WSGI app directly, eliminating flask, though again, I can't see what difference that would make:
```python
# foo.py
from time import sleep
from os import getpid

def app(environ, start_response):
    print("Entering", getpid())
    sleep(10)
    print("DONE", getpid())
    start_response("200 OK", [('Content-Type', 'text/plain')])
    return [b'Good bye']

# Run with: gunicorn --bind 0.0.0.0:8080 --access-logfile - --error-logfile - foo:app
```

I know that Linux has some different behaviours over the loopback address than it does over "real" sockets; I don't know if macOS does or not. But I also can't reproduce it when I use curl 7.64.0 from a RaspberryPi with Linux 5.4.83 connected through a couple gigabit Unifi switches with 300 clients. It appears to behave identically to the entirely local test (all requests succeed). (One small difference is that localhost curl 7.80 sends 78 header bytes, while remote curl 7.64 sends 81 bytes.)

[Recent versions of curl (since 2008)](https://daniel.haxx.se/blog/2020/02/10/curl-ootw-keepalive-time/) enable TCP keepalives every 60 seconds by default. Watching the network traffic from the Pi to my mac, I see this traffic flowing back on forth on the idle connections, keeping them alive to (eventually) be serviced by the worker. (I presume the same thing would be happening on localhost, but I haven't captured it.) Turning keepalives off with `--no-keepalive` on the client doesn't seem to change anything, at least so far after 670s (nor would I expect it to).

The customizations I make to my kernel settings are below. None of them seem particularly relevant, but 🤷 ?
```ini
# For databases, increase SYSV IPC limits
kern.sysv.shmmax=1073741824
kern.sysv.shmmin=1
kern.sysv.shmmni=4096
kern.sysv.shmseg=32
kern.sysv.shmall=1179648
kern.maxfilesperproc=65536
kern.maxfiles=655360
# speed up time machine
debug.lowpri_throttle_enabled=0

# From https://fasterdata.es.net/host-tuning/osx/
# tuning for gigabit connection speed
# OSX default of 3 is not big enough
net.inet.tcp.win_scale_factor=8
# increase OSX TCP autotuning maximums
net.inet.tcp.autorcvbufmax=33554432
net.inet.tcp.autosndbufmax=33554432

# JAM: Can't seem to increase this above the default 8MB
# kern.ipc.maxsockbuf=16777216

# From https://rolande.wordpress.com/2010/12/30/performance-tuning-the-network-stack-on-mac-osx-10-6/
kern.ipc.somaxconn=2048
net.inet.tcp.sendspace=1042560
net.inet.tcp.recvspace=1042560
# segment size: set to ethernet packet sizes
# divisible by ATM cell size
net.inet.tcp.mssdflt=1448
net.inet.tcp.v6mssdflt=1428
net.inet.tcp.slowstart_flightsize=20
net.inet.tcp.local_slowstart_flightsize=20
```

**Comment by rusiaaman** [comment]
@jamadden thanks for sharing your sysctl config it helped in reproducing the absence of the issue in your system.

I've found that `kern.ipc.somaxconn` setting affects this behavior. It makes a lot of sense now. The default value was 128. Setting it to 2048 and rebooting fixes the issue. Similarly on ubuntu `net.core.somaxconn` was 4096 by default because of which there were no issues, setting it to 128 leads to reproduction of the issue.

Related: uwsgi fails to start if listen parameter (equivalent to backlog parameter in gunicorn) is greater than somaxconn. https://github.com/unbit/uwsgi/pull/18 (Also the default value for listen is just 100 as opposed to 2048 for backlog). It might be worth doing the same for gunicorn.

Thanks for spending time sharing your thoughts, this issue can now be closed if needed.

**Comment by jamadden** [comment]
Ah-hah! I'd forgotten that `kern.ipc.somaxconn` affected true sockets as well as other things. Thanks for the refresher!

I'm glad I was able to be of help!
