### ISSUE TITLE
Gunicorn Not Deflating Memory

### ISSUE THREAD

**Issue by Abhishek-xavi** [benoitc/gunicorn#2783]
Hello Team,

I am using Gunicorn in a container deployment. 
I am using 4 workers and 4 threads. During the execution of a python process, Gunicorn takes roughly 4 GB. But post processing, it still holds back roughly 2.5 GB.
I have tried using --max-request setting but am not observing the workers reset or release memory. 

Need help in understanding how this can be solved. Also, can you please provide info as to what holds on to this memory.(Is this memory being held by local/global variables?)

**Comment by tilgovi** [comment]
We have received similar reports in the past, but never any evidence that Gunicorn leaks memory. It is normal for Python not to release memory sometimes. The interpreter keeps its own private heap so that many allocations can happen without asking the OS for more memory.

You will need to profile the memory usage using Python tools that can tell you what objects are still allocated. Looking at the OS memory does not provide enough information to verify an issue. You might start by looking at the `gc` module ([link](https://docs.python.org/3/library/gc.html)).

One thing to check is whether the memory goes up with every request or if it always returns to same stable level. If it always returns, then there is probably no leak. If it always goes up, there may be a leak, but it may or may not be in Gunicorn code.

**Comment by tilgovi** [comment]
You could also investigate the `tracemalloc` module ([link](https://docs.python.org/3/library/tracemalloc.html#module-tracemalloc)).

**Comment by Abhishek-xavi** [comment]
Thanks Tilgovi!
I will check this out and see if I can get my answer.
