### ISSUE TITLE
Is Gunicorn OK?

### ISSUE THREAD

**Issue by orokusaki** [benoitc/gunicorn#2967]
From the outside, the green unicorn appears to be in need of life support.

  1. there hasn't been a [PyPi update in over 2 years](https://pypi.org/project/gunicorn/#history)
  2. there are hundreds of [open issues](https://github.com/benoitc/gunicorn/issues) and over [100 PRs](https://github.com/benoitc/gunicorn/pulls)
  3. there haven't been [any new tags since the last release](https://github.com/benoitc/gunicorn/tags)...
  4. ...yet, master continues (slowly) [ahead of the latest release](https://github.com/benoitc/gunicorn/compare/20.1.0...master)

Gunicorn remains, for many, the only great choice for production-ready web server process management in ASGI deployments, with many (most? all?) ASGI servers recommending Gunicorn in front of their workers.

Gunicorn is solid enough that it still just works for us (Python 3.11.3), despite no updates in +2 years. So, ignoring the number of GitHub issues and PRs, I'm guessing there aren't **too** many lines of code and docs that need updating, in order to make a release that addresses any security concerns (*if any*) and [official 3.11 support](https://github.com/benoitc/gunicorn/issues/2941).

If there are specific things you (@benoitc or others involved) need help with to get caught up with internal goals, please reply here and let's all talk about this. Could Gunicorn benefit from sponsorship or membership in a cooperative like some of the other popular projects?

**Comment by slocke716** [comment]
Looks like cutting a release is incredibly easy https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes .

Maintainers:
@benoitc 
@sirkonst
@tilgovi 
@berkerpeksag 
@jamadden 
@javabrett 

Could someone please cut a release?

**Comment by tilgovi** [comment]
In the past, I have cut at least some releases, because my understanding was that @benoitc didn't want to be the only one to be able to do that.

That said, the challenging part of making a release is not the actual work of cutting it, it's the project management of deciding when to do so.

At this point, I've been absent enough for long enough that I've lost track of what the state of things is, and loading that context is what's expensive.

We haven't historically had any such rules for when to make a release. We don't have a policy of ensuring that mainline is green. We don't have a commit message policy that ensures breaking changes are easily identified. It's been the manual work of the person cutting a release to figure this stuff out.

I can commit to going through the current set of changes and making a judgment about whether they can be 20.2.0. If not, I'll make a 20.2.0 release from a branch to get the bug fixes out.

What I could use help with is project management for 21.0. There's a milestone on the tracker, but I don't know if those issues are accurate anymore. If you'd like to volunteer, reach out to me directly by email, please, and let me know that you're interested in helping groom the current set open PRs and tickets for high priority things that should make a 21.0 release, and then we can solicit help from the community to move those changes through.

**Comment by tilgovi** [comment]
Please refrain from making suggestions about how to automate any of these things or institute processes that would make this easier. If you really do want to do that, reach out and I'll talk with you about adding maintainers and ideas for improving our workflow, but let's keep this thread to a discussion of getting 20.2.0 and 21.0 out with our current processes.

**Comment by benoitc** [comment]
@tilgovi feel free to ping me if you have any idea on making backlog prioritization better using latest Github enhancements.. Or we can discuss it over a new ticket. Imo we should first ensure that changelog is updated hen a change is commited. Maybe making it a rule for a an accepted PR. but let's discuss it. Any time is OK.

**Comment by orokusaki** [comment]
@benoitc @tilgovi thanks for the responses - I'm excited to hear that there will soon be a release. Also @benoitc, when you get the funding set up, please post about that here (perhaps just a link to your release announcement) as well, because I'll donate that same day. Gunicorn is a prized project in the Python community, and all your (and others here) work on it is very much appreciated.

**Comment by benoitc** [comment]
i am closing this issue. Release is about to land.  Please check https://github.com/benoitc/gunicorn/milestone/20 for the progress :)
