### ISSUE TITLE
option to use SO_REUSEPORT ?

### ISSUE THREAD

**Issue by benoitc** [benoitc/gunicorn#598]
Linux 3.9 added the socket option `SO_REUSEPORT` which is also available in freebsd. Maybe we could have an option to use it or if present, use it. One advantage I see in it is that it would improve the way connections are distributed across processes. 

See the post on LWN for more information:

https://lwn.net/Articles/542629/ 

In which we can read the difference with using SO_REUSEADDR as we do now:

> The problem with this technique, as Tom pointed out, is that when multiple threads are waiting in the accept() call, wake-ups are not fair, so that, under high load, incoming connections may be distributed across threads in a very unbalanced fashion. At Google, they have seen a factor-of-three difference between the thread accepting the most connections and the thread accepting the fewest connections; that sort of imbalance can lead to underutilization of CPU cores. By contrast, the SO_REUSEPORT implementation distributes connections evenly across all of the threads (or processes) that are blocked in accept() on the same port.

Thoughts?

**Comment by dPeS** [comment]
+1 waiting for this, how can I help?

**Comment by berkerpeksag** [comment]
@dPeS you can send a pull request :)

**Comment by cactus** [comment]
I've been fiddling around with a [branch](https://github.com/benoitc/gunicorn/compare/master...cactus:so_reuseport) that attempts to add support for so_reuseport. It hasn't been tested much, and likely needs more work.

**Comment by smilliken** [comment]
Here's a simple commit that enables `SO_REUSEPORT`: https://github.com/smilliken/gunicorn/commit/9e66c7a03fb77a1a8bd88bfc067afed01bc5a7b2

This works on production systems running Python 2.7.9 and various versions of Linux 3.x (before and after 3.9 in which the feature was added). It likely breaks with an `AttributeError` on earlier versions of Python that don't define `socket.SO_REUSEPORT` (untested).

I'm using it for zero-downtime deploys, enabling multiple parent gunicorn processes to run concurrently during a transition, while the old processes finish their requests and exit gracefully. I couldn't use USR2 signal as suggested, since I need to handle environmental changes as well. Specifically, the new gunicorn processes need to be spawned from a new environment to have the correct state. I imagine it would be useful for other environmental changes, like process owner or cgroups.

**Comment by tilgovi** [comment]
@smilliken it would be great if you could open a PR from a branch with that commit. Maybe we should add an option in `gunicorn/config.py`. It could test `hasattr` on the socket module and reject the option if there is no support.

**Comment by smilliken** [comment]
Created pull request.

**Comment by ngrilly** [comment]
@smilliken SO_REUSEPORT is great, but its current implementation in Linux doesn't support zero-downtime deploys:

https://lwn.net/Articles/542866/

**Comment by methane** [comment]
EPOLLEXCLUSIVE can be used to avoid thundering herd.  See #1239.

**Comment by benoitc** [comment]
fixed in #1344
