### ISSUE TITLE
gaiohttpy.py invalid syntax warning (19.0.0)

### ISSUE THREAD

**Issue by hyao** [benoitc/gunicorn#788]
Thanks for the new release!

Just pip installed gunicorn 19.0.0, it installs all right, but there's the following warning during installation (Python 2.7.6):

```
File "/usr/local/lib/python2.7/dist-packages/gunicorn/workers/gaiohttp.py", line 67
        yield from self.wsgi.close()
                 ^
    SyntaxError: invalid syntax
```

Thanks,

**Comment by koobs** [comment]
@asvetlov I'm still seeing this in 19.2.1, but for **_gaiohttp.py**

```
  File "/usr/local/lib/python2.7/site-packages/gunicorn/workers/_gaiohttp.py", line 68
    yield from self.wsgi.close()
             ^
SyntaxError: invalid syntax
```

**Comment by benoitc** [comment]
@koobs which version of gaiohttp did you installed?

**Comment by koobs** [comment]
@benoitc It *was* 0.9.0, but I just updated the FreeBSD port to 0.14.4 for the sake of it.

The real issue is that on Python 2.7 (when aiohttp isnt even installed), compilation of _gaiohttp.py is attempted during build/build-install and that fails, leaving pyc/pyo files missing, but referenced in --record output.

**Comment by koobs** [comment]
@benoitc More precisely, this was likely fixed in 86f740420cb12cf071f7dc7981330353e258931 (unless it didnt *also* cover _aiohttp.py) but then regressed with 719e61bf18ca3347e58c03dbc04156c859659a1d

**Comment by benoitc** [comment]
@koobs err I mean, are you using the latest version of pip? It should be fixed there. Let me know.

**Comment by berkerpeksag** [comment]
Perhaps we can add a small note to the documentation?

**Comment by benoitc** [comment]
@berkerpeksag waiting the split I think It's a good idea :) We should start the split of workers and other plugins asap to release a new version in march.

**Comment by matrixise** [comment]
Yesterday, I just installed the last version, `pip install gunicorn` and I see this error syntax, for me, first thing, I think there is a problem I uninstall this version and try to work with a previous version.

After that, I have read the error and understood that I can use it because it's just a "warning" for pip.

First reaction of a user, uninstall it and use an older version :/

**Comment by berkerpeksag** [comment]
@benoitc yes, good idea. I need to read #837 again :)

**Comment by catskul** [comment]
Still seeing it in 19.3.0

**Comment by berkerpeksag** [comment]
@catskul please update your pip version. The warning is not harmful and recent pip versions don't show it anymore.
